# frozen_string_literal: true
source "https://rubygems.org"

gem "cocoapods"

# So we know if we need to run `pod install`
gem 'cocoapods-check', git: 'https://github.com/square/cocoapods-check.git', branch: 'master'

# To manage our secret keys
gem "cocoapods-keys"

# To apply fixes to the React Native code
gem 'cocoapods-fix-react-native'

# To avoid ambiguous Podfile.lock contents
gem "psych"
