source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

react_path = '../node_modules/react-native'

target 'Emission' do
  pod 'Emission', :path => '../'
  pod 'Extraction'
  pod 'React', :path => react_path, :subspecs => %w(RCTWebSocket RCTImage)
  if ENV['ARTSY_STAFF_MEMBER'] != nil || ENV['CI'] != nil
    pod 'Artsy+UIFonts', :git => "https://github.com/artsy/Artsy-UIFonts.git"
  else
    pod 'Artsy+UIFonts', :git => "https://github.com/artsy/Artsy-OSSUIFonts.git"
  end

  # while: https://github.com/AppHubPlatform/apphub/pull/32
  pod 'AppHub', :git => "https://github.com/orta/apphub.git"

  # Example app only
  pod 'SAMKeychain'
  pod 'Artsy+Authentication', :subspecs => %w(email),
                              :git => 'https://github.com/artsy/Artsy-Authentication.git',
                              :branch => 'fetch-user-details'

  target 'EmissionTests' do
    inherit! :search_paths

    pod 'React', :path => react_path, :subspecs => %w(RCTTest)

    pod 'Specta'
    # pod 'Expecta'
  end
end
