source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Emission_Example' do
  pod 'Emission', :path => '../'
  pod 'React', :path => './node_modules/react-native', :subspecs => %w( Core RCTText RCTWebSocket RCTNetwork )

  if ENV['ARTSY_STAFF_MEMBER'] != nil || ENV['CI'] != nil
    pod 'Artsy+UIFonts', :git => "https://github.com/artsy/Artsy-UIFonts.git"
  else
    pod 'Artsy+UIFonts', :git => "https://github.com/artsy/Artsy-OSSUIFonts.git"
  end

  # This is just to support ARSwitchView from Eigen. This needs to be sorted out
  # before trying to use Emission in Eigen.
  pod 'FLKAutoLayout', :git => 'https://github.com/floriankugler/FLKAutoLayout.git'

  target 'Emission_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8.0'
    pod 'Nimble', '3.0.0'
    pod 'FBSnapshotTestCase', :git => 'https://github.com/neonichu/ios-snapshot-test-case.git'
    pod 'Nimble-Snapshots', '< 4'
  end
end
