import { Itinerary } from "app/Scenes/CityGuide/Screens/Itinerary/utils/itineraryTypes"

/**
 * Compact GraphQL-shaped fixtures for tests. Cast keeps them terse relative to the full
 * generated stop/item unions.
 */
export const MOCK_ITINERARIES = [
  {
    internalID: "chill-vibes-only",
    citySlug: "london-united-kingdom",
    isCurated: true,
    title: "Chill Vibes Only",
    subtitle: "Top picks",
    heroImage: {
      url: "https://picsum.photos/id/1015/800/600.jpg",
      height: null,
      width: null,
      blurhash: null,
    },
    authorName: "Casey Lesser",
    description:
      "Our list of recommendations for the must sees to gallery and museum visits and the hidden gems in between.",
    sections: [
      {
        internalID: "day-1",
        title: "Day 1 — Easing in",
        stops: [
          {
            internalID: "stop-1",
            title: "Coffee at London Cafe",
            address: null,
            category: null,
            note: null,
            isFreeAdmission: null,
            sourceURL: null,
            eventType: null,
            image: { url: "https://picsum.photos/id/1060/200/200.jpg" },
            event: null,
            latitude: 51.5136,
            longitude: -0.1365,
            startTime: "10am",
            endTime: null,
            startAtISO: null,
            endAtISO: null,
            item: null,
          },
          {
            internalID: "stop-2",
            title: "Splash: Sea, Beach and Pool",
            address: "Atlas Gallery, Marylebone",
            category: "SHOW",
            note: "🥂 🧀",
            isFreeAdmission: null,
            sourceURL: null,
            eventType: null,
            image: { url: "https://picsum.photos/id/1040/200/200.jpg" },
            event: null,
            latitude: 51.5185,
            longitude: -0.156,
            startTime: "11am",
            endTime: "4pm",
            startAtISO: null,
            endAtISO: null,
            item: {
              __typename: "Show",
              slug: "atlas-gallery-splash-sea-beach-and-pool",
              name: "Splash: Sea, Beach and Pool",
              href: "/show/atlas-gallery-splash-sea-beach-and-pool",
              isFreeAdmission: null,
              coverImage: null,
              partner: null,
              location: null,
            },
          },
          {
            internalID: "stop-3",
            title: "Georg Baselitz: Back Again",
            address: "White Cube Bermondsey",
            category: "SHOW",
            note: null,
            isFreeAdmission: null,
            sourceURL: null,
            eventType: null,
            image: { url: "https://picsum.photos/id/1033/200/200.jpg" },
            event: null,
            latitude: 51.4995,
            longitude: -0.081,
            startTime: "3pm",
            endTime: "4pm",
            startAtISO: null,
            endAtISO: null,
            item: {
              __typename: "Show",
              slug: "white-cube-georg-baselitz-back-again",
              name: "Georg Baselitz: Back Again",
              href: "/show/white-cube-georg-baselitz-back-again",
              isFreeAdmission: null,
              coverImage: null,
              partner: null,
              location: null,
            },
          },
          {
            internalID: "stop-4",
            title: "Victoria Miro",
            address: null,
            category: "GALLERY",
            note: null,
            isFreeAdmission: null,
            sourceURL: null,
            eventType: null,
            image: { url: "https://picsum.photos/id/1074/200/200.jpg" },
            event: null,
            latitude: 51.532,
            longitude: -0.095,
            startTime: "6pm",
            endTime: "9pm",
            startAtISO: null,
            endAtISO: null,
            item: {
              __typename: "Location",
              name: "Victoria Miro",
              city: "London",
              address: null,
              coordinates: { lat: 51.532, lng: -0.095 },
              partner: {
                slug: "victoria-miro",
                name: "Victoria Miro",
                href: "/partner/victoria-miro",
                profile: null,
              },
            },
          },
          {
            internalID: "stop-5",
            title: "Frieze London",
            address: null,
            category: "FAIR",
            note: null,
            isFreeAdmission: null,
            sourceURL: null,
            eventType: null,
            image: { url: "https://picsum.photos/id/1043/200/200.jpg" },
            event: null,
            latitude: 51.535,
            longitude: -0.154,
            startTime: null,
            endTime: null,
            startAtISO: null,
            endAtISO: null,
            item: {
              __typename: "Fair",
              slug: "frieze-london-2025",
              name: "Frieze London",
              href: "/fair/frieze-london-2025",
              image: null,
              location: null,
            },
          },
        ],
      },
    ],
  },
] as unknown as Itinerary[]

/** Keys on both params so /city-guide/paris/... cannot render a London itinerary. */
export const getMockItinerary = (citySlug: string, itineraryId: string): Itinerary | undefined =>
  MOCK_ITINERARIES.find(
    (itinerary) => itinerary.internalID === itineraryId && itinerary.citySlug === citySlug
  )
