approvedGitRepositories:
  - "**"

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 1440

npmPreapprovedPackages:
  - "@artsy/changelog"
  - "@artsy/cohesion"
  - "@artsy/icons"
  - "@artsy/palette-mobile"
  - "@artsy/to-title-case"
  - "@artsy/update-repo"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
