nodeLinker: node-modules

npmMinimalAgeGate: 1440 # 1 day in minutes (24 * 60)

npmPreapprovedPackages:
  [
    "@artsy/cohesion",
    "@artsy/icons",
    "@artsy/palette-mobile",
    "@artsy/to-title-case",
    "@artsy/update-repo",
  ]

enableScripts: false # Disable postinstall scripts from 3rd parties

yarnPath: .yarn/releases/yarn-4.10.3.cjs
