#!/usr/bin/env bash
set -euxo pipefail


# When to use this script:
#
# Use this script when you want to reset your development environment to a clean state.
# This is useful when you are experiencing issues that may be related to corrupted
# caches, outdated dependencies, or other environmental problems.
# Also super useful when a major dependency upgrade has occurred
# (e.g. React Native, react-native-reanimated upgrade).


echo 'Clear node modules (┛ಠ_ಠ)┛彡┻━┻'
rm -rf node_modules

echo "Clear caches (linting and metro) (┛◉Д◉)┛彡┻━┻"
rm -rf .cache
rm -rf "$TMPDIR/metro*"

echo "Clear hastemap (╯ರ ~ ರ）╯︵ ┻━┻"
rm -rf "$TMPDIR/haste-map-*"

echo "Clear CocoaPods cache (ノಠ益ಠ)ノ彡┻━┻"
rm -rf ~/Library/Caches/CocoaPods

echo 'Clear Xcode derived data (╯°□°)╯︵ ┻━┻'
# sometimes this fails on first try even with -rf
# but a second try takes it home
if ! rm -rf ~/Library/Developer/Xcode/DerivedData; then
	rm -rf ~/Library/Developer/Xcode/DerivedData
fi

echo "Clear Gems (┛ಠ_ಠ)┛彡┻━┻"
rm -rf .vendor

echo "Reinstall dependencies ┬─┬ノ( º _ ºノ)"

yarn

bundle install

yarn setup:artsy

yarn install:all
