#!/usr/bin/env bash
set -euxo pipefail


# Clear local caches and build files

echo 'Clear gradle cache'
if [ -d node_modules ]; then
	cd android
	./gradlew clean
	cd -
fi

echo 'Clear JS caches (┛ಠ_ಠ)┛彡┻━┻'
rm -rf .cache

echo 'Clear gems (┛ಠ_ಠ)┛彡┻━┻'
rm -rf .vendor

echo 'Clear node modules (┛ಠ_ಠ)┛彡┻━┻'
rm -rf node_modules

echo 'Clear cocoapods directory (ノಠ益ಠ)ノ彡┻━┻'
rm -rf Pods

echo 'Clear Xcode derived data (╯°□°)╯︵ ┻━┻'
# sometimes this fails on first try even with -rf
# but a second try takes it home
if ! rm -rf ~/Library/Developer/Xcode/DerivedData; then
	rm -rf ~/Library/Developer/Xcode/DerivedData
fi

echo 'Clear relay, relay query map, jest, and metro caches (┛◉Д◉)┛彡┻━┻'
rm -rf "$TMPDIR"/RelayFindGraphQLTags-*
rm -rf data/complete.queryMap.json
rm -rf .cache
rm -rf "$TMPDIR"/metro*
rm -rf src/__generated__/*.graphql.ts
yarn local-palette-dev:stop


echo 'Clear build artefacts (╯ರ ~ ರ）╯︵ ┻━┻'
find dist/ ! -name '.gitkeep' -type f -exec rm -f {} +

echo 'Reinstall dependencies ┬─┬ノ( º _ ºノ)'
yarn install:all

./scripts/setup/update-echo

yarn pod-install-repo-update
