name: Setup JavaScript environment
description: "Set up Node.js, install dependencies, and run relay compiler"
runs:
  using: "composite"
  steps:
    - name: Setup node.js
      uses: ./.github/actions/setup-node

    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: .yarn/cache
        key: yarn-v4-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-v4-${{ runner.os }}-

    - name: Install Node.js dependencies
      run: yarn install --immutable
      shell: bash

    - name: Run relay compiler
      run: yarn relay
      shell: bash
