#!/usr/bin/env bash

if ! command -v yalc &> /dev/null
then
    echo "Error unlinking @artsy/palette-mobile for dev. 'yalc' is not installed. Please install it with 'yarn global add yalc'."
    echo "See https://docs.joshuatz.com/cheatsheets/devops/yalc/ for more info."
    exit
fi

yalc remove @artsy/palette-mobile
yarn install
