export const countries = [
  {
    name: "Afghanistan (‫افغانستان‬‎)",
    iso2: "af",
    flag: require("@images/flags/af.png"),
    dialCode: "93",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 32225560,
    areaCodes: null,
  },
  {
    name: "Albania (Shqipëri)",
    iso2: "al",
    flag: require("@images/flags/al.png"),
    dialCode: "355",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2845955,
    areaCodes: null,
  },
  {
    name: "Algeria (‫الجزائر‬‎)",
    iso2: "dz",
    flag: require("@images/flags/dz.png"),
    dialCode: "213",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 43000000,
    areaCodes: null,
  },
  {
    name: "American Samoa",
    iso2: "as",
    flag: require("@images/flags/as.png"),
    dialCode: "1684",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 56700,
    areaCodes: null,
  },
  {
    name: "Andorra",
    iso2: "ad",
    flag: require("@images/flags/ad.png"),
    dialCode: "376",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 77543,
    areaCodes: null,
  },
  {
    name: "Angola",
    iso2: "ao",
    flag: require("@images/flags/ao.png"),
    dialCode: "244",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 31127674,
    areaCodes: null,
  },
  {
    name: "Anguilla",
    iso2: "ai",
    flag: require("@images/flags/ai.png"),
    dialCode: "1264",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 14869,
    areaCodes: null,
  },
  {
    name: "Antigua and Barbuda",
    iso2: "ag",
    flag: require("@images/flags/ag.png"),
    dialCode: "1268",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 96453,
    areaCodes: null,
  },
  {
    name: "Argentina",
    iso2: "ar",
    flag: require("@images/flags/ar.png"),
    dialCode: "54",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 45376763,
    areaCodes: null,
  },
  {
    name: "Armenia (Հայաստան)",
    iso2: "am",
    flag: require("@images/flags/am.png"),
    dialCode: "374",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2956900,
    areaCodes: null,
  },
  {
    name: "Aruba",
    iso2: "aw",
    flag: require("@images/flags/aw.png"),
    dialCode: "297",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 112190,
    areaCodes: null,
  },
  {
    name: "Australia",
    iso2: "au",
    flag: require("@images/flags/au.png"),
    dialCode: "61",
    trunkPrefix: "0",
    internationalPrefixes: ["0011", "0015", "0014", "0018", "0019"],
    priority: 25756880,
    areaCodes: null,
  },
  {
    name: "Austria (Österreich)",
    iso2: "at",
    flag: require("@images/flags/at.png"),
    dialCode: "43",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 8902600,
    areaCodes: null,
  },
  {
    name: "Azerbaijan (Azərbaycan)",
    iso2: "az",
    flag: require("@images/flags/az.png"),
    dialCode: "994",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 10067108,
    areaCodes: null,
  },
  {
    name: "Bahamas",
    iso2: "bs",
    flag: require("@images/flags/bs.png"),
    dialCode: "1242",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 385340,
    areaCodes: null,
  },
  {
    name: "Bahrain (‫البحرين‬‎)",
    iso2: "bh",
    flag: require("@images/flags/bh.png"),
    dialCode: "973",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1543300,
    areaCodes: null,
  },
  {
    name: "Bangladesh (বাংলাদেশ)",
    iso2: "bd",
    flag: require("@images/flags/bd.png"),
    dialCode: "880",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 168872634,
    areaCodes: null,
  },
  {
    name: "Barbados",
    iso2: "bb",
    flag: require("@images/flags/bb.png"),
    dialCode: "1246",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 287025,
    areaCodes: null,
  },
  {
    name: "Belarus (Беларусь)",
    iso2: "by",
    flag: require("@images/flags/by.png"),
    dialCode: "375",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 9397800,
    areaCodes: null,
  },
  {
    name: "Belgium (België)",
    iso2: "be",
    flag: require("@images/flags/be.png"),
    dialCode: "32",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 11528375,
    areaCodes: null,
  },
  {
    name: "Belize",
    iso2: "bz",
    flag: require("@images/flags/bz.png"),
    dialCode: "501",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 408487,
    areaCodes: null,
  },
  {
    name: "Benin (Bénin)",
    iso2: "bj",
    flag: require("@images/flags/bj.png"),
    dialCode: "229",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 11733059,
    areaCodes: null,
  },
  {
    name: "Bermuda",
    iso2: "bm",
    flag: require("@images/flags/bm.png"),
    dialCode: "1441",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 64027,
    areaCodes: null,
  },
  {
    name: "Bhutan (འབྲུག)",
    iso2: "bt",
    flag: require("@images/flags/bt.png"),
    dialCode: "975",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 741672,
    areaCodes: null,
  },
  {
    name: "Bolivia",
    iso2: "bo",
    flag: require("@images/flags/bo.png"),
    dialCode: "591",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 11469896,
    areaCodes: null,
  },
  {
    name: "Bosnia and Herzegovina (Босна и Херцеговина)",
    iso2: "ba",
    flag: require("@images/flags/ba.png"),
    dialCode: "387",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 3301000,
    areaCodes: null,
  },
  {
    name: "Botswana",
    iso2: "bw",
    flag: require("@images/flags/bw.png"),
    dialCode: "267",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2338851,
    areaCodes: null,
  },
  {
    name: "Brazil (Brasil)",
    iso2: "br",
    flag: require("@images/flags/br.png"),
    dialCode: "55",
    trunkPrefix: "0",
    internationalPrefixes: ["0015", "0021", "0031", "0041"],
    priority: 211729470,
    areaCodes: null,
  },
  {
    name: "British Indian Ocean Territory",
    iso2: "io",
    flag: require("@images/flags/io.png"),
    dialCode: "246",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 0,
    areaCodes: null,
  },
  {
    name: "British Virgin Islands",
    iso2: "vg",
    flag: require("@images/flags/vg.png"),
    dialCode: "1284",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 104578,
    areaCodes: null,
  },
  {
    name: "Brunei",
    iso2: "bn",
    flag: require("@images/flags/bn.png"),
    dialCode: "673",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 459500,
    areaCodes: null,
  },
  {
    name: "Bulgaria (България)",
    iso2: "bg",
    flag: require("@images/flags/bg.png"),
    dialCode: "359",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 6951482,
    areaCodes: null,
  },
  {
    name: "Burkina Faso",
    iso2: "bf",
    flag: require("@images/flags/bf.png"),
    dialCode: "226",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 21510181,
    areaCodes: null,
  },
  {
    name: "Burundi (Uburundi)",
    iso2: "bi",
    flag: require("@images/flags/bi.png"),
    dialCode: "257",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 10953317,
    areaCodes: null,
  },
  {
    name: "Cambodia (កម្ពុជា)",
    iso2: "kh",
    flag: require("@images/flags/kh.png"),
    dialCode: "855",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 15288489,
    areaCodes: null,
  },
  {
    name: "Cameroon (Cameroun)",
    iso2: "cm",
    flag: require("@images/flags/cm.png"),
    dialCode: "237",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 26545864,
    areaCodes: null,
  },
  {
    name: "Canada",
    iso2: "ca",
    flag: require("@images/flags/ca.png"),
    dialCode: "1",
    trunkPrefix: "1",
    internationalPrefixes: ["011"],
    priority: 38083197,
    areaCodes: [
      "204",
      "226",
      "236",
      "249",
      "250",
      "289",
      "306",
      "343",
      "365",
      "387",
      "403",
      "416",
      "418",
      "431",
      "437",
      "438",
      "450",
      "506",
      "514",
      "519",
      "548",
      "579",
      "581",
      "587",
      "604",
      "613",
      "639",
      "647",
      "672",
      "705",
      "709",
      "742",
      "778",
      "780",
      "782",
      "807",
      "819",
      "825",
      "867",
      "873",
      "902",
      "905",
    ],
  },
  {
    name: "Cape Verde (Kabu Verdi)",
    iso2: "cv",
    flag: require("@images/flags/cv.png"),
    dialCode: "238",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 550483,
    areaCodes: null,
  },
  {
    name: "Caribbean Netherlands",
    iso2: "bq",
    flag: null,
    dialCode: "599",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1,
    areaCodes: null,
  },
  {
    name: "Cayman Islands",
    iso2: "ky",
    flag: require("@images/flags/ky.png"),
    dialCode: "1345",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 65813,
    areaCodes: null,
  },
  {
    name: "Central African Republic (République centrafricaine)",
    iso2: "cf",
    flag: require("@images/flags/cf.png"),
    dialCode: "236",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 5496011,
    areaCodes: null,
  },
  {
    name: "Chad (Tchad)",
    iso2: "td",
    flag: require("@images/flags/td.png"),
    dialCode: "235",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 16244513,
    areaCodes: null,
  },
  {
    name: "Chile",
    iso2: "cl",
    flag: require("@images/flags/cl.png"),
    dialCode: "56",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 19458310,
    areaCodes: null,
  },
  {
    name: "China (中国)",
    iso2: "cn",
    flag: require("@images/flags/cn.png"),
    dialCode: "86",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 1403322440,
    areaCodes: null,
  },
  {
    name: "Christmas Island",
    iso2: "cx",
    flag: require("@images/flags/cx.png"),
    dialCode: "61",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1955,
    areaCodes: null,
  },
  {
    name: "Cocos (Keeling) Islands",
    iso2: "cc",
    flag: require("@images/flags/cc.png"),
    dialCode: "61",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 500,
    areaCodes: null,
  },
  {
    name: "Colombia",
    iso2: "co",
    flag: require("@images/flags/co.png"),
    dialCode: "57",
    trunkPrefix: "0",
    internationalPrefixes: ["005", "007", "009"],
    priority: 50372424,
    areaCodes: null,
  },
  {
    name: "Comoros (‫جزر القمر‬‎)",
    iso2: "km",
    flag: require("@images/flags/km.png"),
    dialCode: "269",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 873724,
    areaCodes: null,
  },
  {
    name: "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)",
    iso2: "cd",
    flag: require("@images/flags/cd.png"),
    dialCode: "243",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 89561404,
    areaCodes: null,
  },
  {
    name: "Congo (Republic) (Congo-Brazzaville)",
    iso2: "cg",
    flag: require("@images/flags/cg.png"),
    dialCode: "242",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 5518092,
    areaCodes: null,
  },
  {
    name: "Cook Islands",
    iso2: "ck",
    flag: require("@images/flags/ck.png"),
    dialCode: "682",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 15200,
    areaCodes: null,
  },
  {
    name: "Costa Rica",
    iso2: "cr",
    flag: require("@images/flags/cr.png"),
    dialCode: "506",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 5058007,
    areaCodes: null,
  },
  {
    name: "Côte d’Ivoire",
    iso2: "ci",
    flag: require("@images/flags/ci.png"),
    dialCode: "225",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 25823071,
    areaCodes: null,
  },
  {
    name: "Croatia (Hrvatska)",
    iso2: "hr",
    flag: require("@images/flags/hr.png"),
    dialCode: "385",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 4076246,
    areaCodes: null,
  },
  {
    name: "Cuba",
    iso2: "cu",
    flag: require("@images/flags/cu.png"),
    dialCode: "53",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 11193470,
    areaCodes: null,
  },
  {
    name: "Curaçao",
    iso2: "cw",
    flag: require("@images/flags/cw.png"),
    dialCode: "599",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 0,
    areaCodes: null,
  },
  {
    name: "Cyprus (Κύπρος)",
    iso2: "cy",
    flag: require("@images/flags/cy.png"),
    dialCode: "357",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 875900,
    areaCodes: null,
  },
  {
    name: "Czech Republic (Česká republika)",
    iso2: "cz",
    flag: require("@images/flags/cz.png"),
    dialCode: "420",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 10693939,
    areaCodes: null,
  },
  {
    name: "Denmark (Danmark)",
    iso2: "dk",
    flag: require("@images/flags/dk.png"),
    dialCode: "45",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 5824857,
    areaCodes: null,
  },
  {
    name: "Djibouti",
    iso2: "dj",
    flag: require("@images/flags/dj.png"),
    dialCode: "253",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1078373,
    areaCodes: null,
  },
  {
    name: "Dominica",
    iso2: "dm",
    flag: require("@images/flags/dm.png"),
    dialCode: "1767",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 71808,
    areaCodes: null,
  },
  {
    name: "Dominican Republic (República Dominicana)",
    iso2: "do",
    flag: require("@images/flags/do.png"),
    dialCode: "1",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 10448499,
    areaCodes: ["809", "829", "849"],
  },
  {
    name: "Ecuador",
    iso2: "ec",
    flag: require("@images/flags/ec.png"),
    dialCode: "593",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 17516888,
    areaCodes: null,
  },
  {
    name: "Egypt (‫مصر‬‎)",
    iso2: "eg",
    flag: require("@images/flags/eg.png"),
    dialCode: "20",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 100554998,
    areaCodes: null,
  },
  {
    name: "El Salvador",
    iso2: "sv",
    flag: require("@images/flags/sv.png"),
    dialCode: "503",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 6486201,
    areaCodes: null,
  },
  {
    name: "Equatorial Guinea (Guinea Ecuatorial)",
    iso2: "gq",
    flag: require("@images/flags/gq.png"),
    dialCode: "240",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1454789,
    areaCodes: null,
  },
  {
    name: "Eritrea",
    iso2: "er",
    flag: require("@images/flags/er.png"),
    dialCode: "291",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 3497117,
    areaCodes: null,
  },
  {
    name: "Estonia (Eesti)",
    iso2: "ee",
    flag: require("@images/flags/ee.png"),
    dialCode: "372",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1328976,
    areaCodes: null,
  },
  {
    name: "Ethiopia",
    iso2: "et",
    flag: require("@images/flags/et.png"),
    dialCode: "251",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 98665000,
    areaCodes: null,
  },
  {
    name: "Falkland Islands (Islas Malvinas)",
    iso2: "fk",
    flag: require("@images/flags/fk.png"),
    dialCode: "500",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 3198,
    areaCodes: null,
  },
  {
    name: "Faroe Islands (Føroyar)",
    iso2: "fo",
    flag: require("@images/flags/fo.png"),
    dialCode: "298",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 52484,
    areaCodes: null,
  },
  {
    name: "Fiji",
    iso2: "fj",
    flag: require("@images/flags/fj.png"),
    dialCode: "679",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 884887,
    areaCodes: null,
  },
  {
    name: "Finland (Suomi)",
    iso2: "fi",
    flag: require("@images/flags/fi.png"),
    dialCode: "358",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 5498027,
    areaCodes: null,
  },
  {
    name: "France",
    iso2: "fr",
    flag: require("@images/flags/fr.png"),
    dialCode: "33",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 67067000,
    areaCodes: null,
  },
  {
    name: "French Guiana (Guyane française)",
    iso2: "gf",
    flag: require("@images/flags/gf.png"),
    dialCode: "594",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 290691,
    areaCodes: null,
  },
  {
    name: "French Polynesia (Polynésie française)",
    iso2: "pf",
    flag: require("@images/flags/pf.png"),
    dialCode: "689",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 275918,
    areaCodes: null,
  },
  {
    name: "Gabon",
    iso2: "ga",
    flag: require("@images/flags/ga.png"),
    dialCode: "241",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2172579,
    areaCodes: null,
  },
  {
    name: "Gambia",
    iso2: "gm",
    flag: require("@images/flags/gm.png"),
    dialCode: "220",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2347706,
    areaCodes: null,
  },
  {
    name: "Georgia (საქართველო)",
    iso2: "ge",
    flag: require("@images/flags/ge.png"),
    dialCode: "995",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 3716858,
    areaCodes: null,
  },
  {
    name: "Germany (Deutschland)",
    iso2: "de",
    flag: require("@images/flags/de.png"),
    dialCode: "49",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 83166711,
    areaCodes: null,
  },
  {
    name: "Ghana (Gaana)",
    iso2: "gh",
    flag: require("@images/flags/gh.png"),
    dialCode: "233",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 30280811,
    areaCodes: null,
  },
  {
    name: "Gibraltar",
    iso2: "gi",
    flag: require("@images/flags/gi.png"),
    dialCode: "350",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 33691,
    areaCodes: null,
  },
  {
    name: "Greece (Ελλάδα)",
    iso2: "gr",
    flag: require("@images/flags/gr.png"),
    dialCode: "30",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 10724599,
    areaCodes: null,
  },
  {
    name: "Greenland (Kalaallit Nunaat)",
    iso2: "gl",
    flag: require("@images/flags/gl.png"),
    dialCode: "299",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 56081,
    areaCodes: null,
  },
  {
    name: "Grenada",
    iso2: "gd",
    flag: require("@images/flags/gd.png"),
    dialCode: "1473",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 112003,
    areaCodes: null,
  },
  {
    name: "Guadeloupe",
    iso2: "gp",
    flag: require("@images/flags/gp.png"),
    dialCode: "590",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 395700,
    areaCodes: null,
  },
  {
    name: "Guam",
    iso2: "gu",
    flag: require("@images/flags/gu.png"),
    dialCode: "1671",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 172400,
    areaCodes: null,
  },
  {
    name: "Guatemala",
    iso2: "gt",
    flag: require("@images/flags/gt.png"),
    dialCode: "502",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 16604026,
    areaCodes: null,
  },
  {
    name: "Guernsey",
    iso2: "gg",
    flag: require("@images/flags/gg.png"),
    dialCode: "44",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 63196,
    areaCodes: null,
  },
  {
    name: "Guinea (Guinée)",
    iso2: "gn",
    flag: require("@images/flags/gn.png"),
    dialCode: "224",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 12218357,
    areaCodes: null,
  },
  {
    name: "Guinea-Bissau (Guiné Bissau)",
    iso2: "gw",
    flag: require("@images/flags/gw.png"),
    dialCode: "245",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1604528,
    areaCodes: null,
  },
  {
    name: "Guyana",
    iso2: "gy",
    flag: require("@images/flags/gy.png"),
    dialCode: "592",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 782766,
    areaCodes: null,
  },
  {
    name: "Haiti",
    iso2: "ht",
    flag: require("@images/flags/ht.png"),
    dialCode: "509",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 11577779,
    areaCodes: null,
  },
  {
    name: "Honduras",
    iso2: "hn",
    flag: require("@images/flags/hn.png"),
    dialCode: "504",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 9304380,
    areaCodes: null,
  },
  {
    name: "Hong Kong (香港)",
    iso2: "hk",
    flag: require("@images/flags/hk.png"),
    dialCode: "852",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 7500700,
    areaCodes: null,
  },
  {
    name: "Hungary (Magyarország)",
    iso2: "hu",
    flag: require("@images/flags/hu.png"),
    dialCode: "36",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 9769000,
    areaCodes: null,
  },
  {
    name: "Iceland (Ísland)",
    iso2: "is",
    flag: require("@images/flags/is.png"),
    dialCode: "354",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 366130,
    areaCodes: null,
  },
  {
    name: "India (भारत)",
    iso2: "in",
    flag: require("@images/flags/in.png"),
    dialCode: "91",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 1364120059,
    areaCodes: null,
  },
  {
    name: "Indonesia",
    iso2: "id",
    flag: require("@images/flags/id.png"),
    dialCode: "62",
    trunkPrefix: "0",
    internationalPrefixes: ["001", "007", "008", "009"],
    priority: 269603400,
    areaCodes: null,
  },
  {
    name: "Iran (‫ایران‬‎)",
    iso2: "ir",
    flag: require("@images/flags/ir.png"),
    dialCode: "98",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 83573873,
    areaCodes: null,
  },
  {
    name: "Iraq (‫العراق‬‎)",
    iso2: "iq",
    flag: require("@images/flags/iq.png"),
    dialCode: "964",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 40150200,
    areaCodes: null,
  },
  {
    name: "Ireland",
    iso2: "ie",
    flag: require("@images/flags/ie.png"),
    dialCode: "353",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 4921500,
    areaCodes: null,
  },
  {
    name: "Isle of Man",
    iso2: "im",
    flag: require("@images/flags/im.png"),
    dialCode: "44",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 83314,
    areaCodes: null,
  },
  {
    name: "Israel (‫ישראל‬‎)",
    iso2: "il",
    flag: require("@images/flags/il.png"),
    dialCode: "972",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 9216070,
    areaCodes: null,
  },
  {
    name: "Italy (Italia)",
    iso2: "it",
    flag: require("@images/flags/it.png"),
    dialCode: "39",
    trunkPrefix: null,
    internationalPrefixes: ["00"],
    priority: 60238522,
    areaCodes: null,
  },
  {
    name: "Jamaica",
    iso2: "jm",
    flag: require("@images/flags/jm.png"),
    dialCode: "1876",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2726667,
    areaCodes: null,
  },
  {
    name: "Japan (日本)",
    iso2: "jp",
    flag: require("@images/flags/jp.png"),
    dialCode: "81",
    trunkPrefix: "0",
    internationalPrefixes: ["010"],
    priority: 125930000,
    areaCodes: null,
  },
  {
    name: "Jersey",
    iso2: "je",
    flag: require("@images/flags/je.png"),
    dialCode: "44",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 106800,
    areaCodes: null,
  },
  {
    name: "Jordan (‫الأردن‬‎)",
    iso2: "jo",
    flag: require("@images/flags/jo.png"),
    dialCode: "962",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 10713832,
    areaCodes: null,
  },
  {
    name: "Kazakhstan (Казахстан)",
    iso2: "kz",
    flag: require("@images/flags/kz.png"),
    dialCode: "77",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 18729296,
    areaCodes: null,
  },
  {
    name: "Kenya",
    iso2: "ke",
    flag: require("@images/flags/ke.png"),
    dialCode: "254",
    trunkPrefix: "0",
    internationalPrefixes: ["000"],
    priority: 47564296,
    areaCodes: null,
  },
  {
    name: "Kiribati",
    iso2: "ki",
    flag: require("@images/flags/ki.png"),
    dialCode: "686",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 120100,
    areaCodes: null,
  },
  {
    name: "Kuwait (‫الكويت‬‎)",
    iso2: "kw",
    flag: require("@images/flags/kw.png"),
    dialCode: "965",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 4420110,
    areaCodes: null,
  },
  {
    name: "Kyrgyzstan (Кыргызстан)",
    iso2: "kg",
    flag: require("@images/flags/kg.png"),
    dialCode: "996",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 6533500,
    areaCodes: null,
  },
  {
    name: "Laos (ລາວ)",
    iso2: "la",
    flag: require("@images/flags/la.png"),
    dialCode: "856",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 7123205,
    areaCodes: null,
  },
  {
    name: "Latvia (Latvija)",
    iso2: "lv",
    flag: require("@images/flags/lv.png"),
    dialCode: "371",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1904600,
    areaCodes: null,
  },
  {
    name: "Lebanon (‫لبنان‬‎)",
    iso2: "lb",
    flag: require("@images/flags/lb.png"),
    dialCode: "961",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 6825442,
    areaCodes: null,
  },
  {
    name: "Lesotho",
    iso2: "ls",
    flag: require("@images/flags/ls.png"),
    dialCode: "266",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2007201,
    areaCodes: null,
  },
  {
    name: "Liberia",
    iso2: "lr",
    flag: require("@images/flags/lr.png"),
    dialCode: "231",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 4475353,
    areaCodes: null,
  },
  {
    name: "Libya (‫ليبيا‬‎)",
    iso2: "ly",
    flag: require("@images/flags/ly.png"),
    dialCode: "218",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 6871287,
    areaCodes: null,
  },
  {
    name: "Liechtenstein",
    iso2: "li",
    flag: require("@images/flags/li.png"),
    dialCode: "423",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 38749,
    areaCodes: null,
  },
  {
    name: "Lithuania (Lietuva)",
    iso2: "lt",
    flag: require("@images/flags/lt.png"),
    dialCode: "370",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2793353,
    areaCodes: null,
  },
  {
    name: "Luxembourg",
    iso2: "lu",
    flag: require("@images/flags/lu.png"),
    dialCode: "352",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 626108,
    areaCodes: null,
  },
  {
    name: "Macau (澳門)",
    iso2: "mo",
    flag: require("@images/flags/mo.png"),
    dialCode: "853",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 696100,
    areaCodes: null,
  },
  {
    name: "Macedonia (FYROM) (Македонија)",
    iso2: "mk",
    flag: require("@images/flags/mk.png"),
    dialCode: "389",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2077132,
    areaCodes: null,
  },
  {
    name: "Madagascar (Madagasikara)",
    iso2: "mg",
    flag: require("@images/flags/mg.png"),
    dialCode: "261",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 26251309,
    areaCodes: null,
  },
  {
    name: "Malawi",
    iso2: "mw",
    flag: require("@images/flags/mw.png"),
    dialCode: "265",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 19129952,
    areaCodes: null,
  },
  {
    name: "Malaysia",
    iso2: "my",
    flag: require("@images/flags/my.png"),
    dialCode: "60",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 32826760,
    areaCodes: null,
  },
  {
    name: "Maldives",
    iso2: "mv",
    flag: require("@images/flags/mv.png"),
    dialCode: "960",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 374775,
    areaCodes: null,
  },
  {
    name: "Mali",
    iso2: "ml",
    flag: require("@images/flags/ml.png"),
    dialCode: "223",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 20250833,
    areaCodes: null,
  },
  {
    name: "Malta",
    iso2: "mt",
    flag: require("@images/flags/mt.png"),
    dialCode: "356",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 493559,
    areaCodes: null,
  },
  {
    name: "Marshall Islands",
    iso2: "mh",
    flag: require("@images/flags/mh.png"),
    dialCode: "692",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 55500,
    areaCodes: null,
  },
  {
    name: "Martinique",
    iso2: "mq",
    flag: require("@images/flags/mq.png"),
    dialCode: "596",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 30066648,
    areaCodes: null,
  },
  {
    name: "Mauritania (‫موريتانيا‬‎)",
    iso2: "mr",
    flag: require("@images/flags/mr.png"),
    dialCode: "222",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 4077347,
    areaCodes: null,
  },
  {
    name: "Mauritius (Moris)",
    iso2: "mu",
    flag: require("@images/flags/mu.png"),
    dialCode: "230",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1265475,
    areaCodes: null,
  },
  {
    name: "Mayotte",
    iso2: "yt",
    flag: require("@images/flags/yt.png"),
    dialCode: "262",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 270372,
    areaCodes: null,
  },
  {
    name: "Mexico (México)",
    iso2: "mx",
    flag: require("@images/flags/mx.png"),
    dialCode: "52",
    trunkPrefix: "01",
    internationalPrefixes: ["00"],
    priority: 127792286,
    areaCodes: null,
  },
  {
    name: "Micronesia",
    iso2: "fm",
    flag: require("@images/flags/fm.png"),
    dialCode: "691",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 104468,
    areaCodes: null,
  },
  {
    name: "Moldova (Republica Moldova)",
    iso2: "md",
    flag: require("@images/flags/md.png"),
    dialCode: "373",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2640400,
    areaCodes: null,
  },
  {
    name: "Monaco",
    iso2: "mc",
    flag: require("@images/flags/mc.png"),
    dialCode: "377",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 38100,
    areaCodes: null,
  },
  {
    name: "Mongolia (Монгол)",
    iso2: "mn",
    flag: require("@images/flags/mn.png"),
    dialCode: "976",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 3325178,
    areaCodes: null,
  },
  {
    name: "Montenegro (Crna Gora)",
    iso2: "me",
    flag: require("@images/flags/me.png"),
    dialCode: "382",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 622359,
    areaCodes: null,
  },
  {
    name: "Montserrat",
    iso2: "ms",
    flag: require("@images/flags/ms.png"),
    dialCode: "1664",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 4989,
    areaCodes: null,
  },
  {
    name: "Morocco (‫المغرب‬‎)",
    iso2: "ma",
    flag: require("@images/flags/ma.png"),
    dialCode: "212",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 35942525,
    areaCodes: null,
  },
  {
    name: "Mozambique (Moçambique)",
    iso2: "mz",
    flag: require("@images/flags/mz.png"),
    dialCode: "258",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 30066648,
    areaCodes: null,
  },
  {
    name: "Myanmar (Burma)",
    iso2: "mm",
    flag: require("@images/flags/mm.png"),
    dialCode: "95",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 54817919,
    areaCodes: null,
  },
  {
    name: "Namibia (Namibië)",
    iso2: "na",
    flag: require("@images/flags/na.png"),
    dialCode: "264",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2458936,
    areaCodes: null,
  },
  {
    name: "Nauru",
    iso2: "nr",
    flag: require("@images/flags/nr.png"),
    dialCode: "674",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 11000,
    areaCodes: null,
  },
  {
    name: "Nepal (नेपाल)",
    iso2: "np",
    flag: require("@images/flags/np.png"),
    dialCode: "977",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 29996478,
    areaCodes: null,
  },
  {
    name: "Netherlands (Nederland)",
    iso2: "nl",
    flag: require("@images/flags/nl.png"),
    dialCode: "31",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 17482181,
    areaCodes: null,
  },
  {
    name: "New Caledonia (Nouvelle-Calédonie)",
    iso2: "nc",
    flag: require("@images/flags/nc.png"),
    dialCode: "687",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 271407,
    areaCodes: null,
  },
  {
    name: "New Zealand",
    iso2: "nz",
    flag: require("@images/flags/nz.png"),
    dialCode: "64",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 5008365,
    areaCodes: null,
  },
  {
    name: "Nicaragua",
    iso2: "ni",
    flag: require("@images/flags/ni.png"),
    dialCode: "505",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 6460411,
    areaCodes: null,
  },
  {
    name: "Niger (Nijar)",
    iso2: "ne",
    flag: require("@images/flags/ne.png"),
    dialCode: "227",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 22314743,
    areaCodes: null,
  },
  {
    name: "Nigeria",
    iso2: "ng",
    flag: require("@images/flags/ng.png"),
    dialCode: "234",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 206139587,
    areaCodes: null,
  },
  {
    name: "Niue",
    iso2: "nu",
    flag: require("@images/flags/nu.png"),
    dialCode: "683",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1520,
    areaCodes: null,
  },
  {
    name: "Norfolk Island",
    iso2: "nf",
    flag: require("@images/flags/nf.png"),
    dialCode: "672",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2169,
    areaCodes: null,
  },
  {
    name: "North Korea (조선 민주주의 인민 공화국)",
    iso2: "kp",
    flag: require("@images/flags/kp.png"),
    dialCode: "850",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 25450000,
    areaCodes: null,
  },
  {
    name: "Northern Mariana Islands",
    iso2: "mp",
    flag: require("@images/flags/mp.png"),
    dialCode: "1670",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 56200,
    areaCodes: null,
  },
  {
    name: "Norway (Norge)",
    iso2: "no",
    flag: require("@images/flags/no.png"),
    dialCode: "47",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 5372355,
    areaCodes: null,
  },
  {
    name: "Oman (‫عُمان‬‎)",
    iso2: "om",
    flag: require("@images/flags/om.png"),
    dialCode: "968",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 4645249,
    areaCodes: null,
  },
  {
    name: "Pakistan (‫پاکستان‬‎)",
    iso2: "pk",
    flag: require("@images/flags/pk.png"),
    dialCode: "92",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 220892331,
    areaCodes: null,
  },
  {
    name: "Palau",
    iso2: "pw",
    flag: require("@images/flags/pw.png"),
    dialCode: "680",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 17900,
    areaCodes: null,
  },
  {
    name: "Palestine (‫فلسطين‬‎)",
    iso2: "ps",
    flag: require("@images/flags/ps.png"),
    dialCode: "970",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 4976684,
    areaCodes: null,
  },
  {
    name: "Panama (Panamá)",
    iso2: "pa",
    flag: require("@images/flags/pa.png"),
    dialCode: "507",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 4218808,
    areaCodes: null,
  },
  {
    name: "Papua New Guinea",
    iso2: "pg",
    flag: require("@images/flags/pg.png"),
    dialCode: "675",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 8935000,
    areaCodes: null,
  },
  {
    name: "Paraguay",
    iso2: "py",
    flag: require("@images/flags/py.png"),
    dialCode: "595",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 7252672,
    areaCodes: null,
  },
  {
    name: "Peru (Perú)",
    iso2: "pe",
    flag: require("@images/flags/pe.png"),
    dialCode: "51",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 32824358,
    areaCodes: null,
  },
  {
    name: "Philippines",
    iso2: "ph",
    flag: require("@images/flags/ph.png"),
    dialCode: "63",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 108829500,
    areaCodes: null,
  },
  {
    name: "Poland (Polska)",
    iso2: "pl",
    flag: require("@images/flags/pl.png"),
    dialCode: "48",
    trunkPrefix: null,
    internationalPrefixes: ["00"],
    priority: 38379000,
    areaCodes: null,
  },
  {
    name: "Portugal",
    iso2: "pt",
    flag: require("@images/flags/pt.png"),
    dialCode: "351",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 10295909,
    areaCodes: null,
  },
  {
    name: "Puerto Rico",
    iso2: "pr",
    flag: require("@images/flags/pr.png"),
    dialCode: "1",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 3193694,
    areaCodes: ["787", "939"],
  },
  {
    name: "Qatar (‫قطر‬‎)",
    iso2: "qa",
    flag: require("@images/flags/qa.png"),
    dialCode: "974",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2795484,
    areaCodes: null,
  },
  {
    name: "Réunion (La Réunion)",
    iso2: "re",
    flag: require("@images/flags/re.png"),
    dialCode: "262",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 859959,
    areaCodes: null,
  },
  {
    name: "Romania (România)",
    iso2: "ro",
    flag: require("@images/flags/ro.png"),
    dialCode: "40",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 19405156,
    areaCodes: null,
  },
  {
    name: "Russia (Россия)",
    iso2: "ru",
    flag: require("@images/flags/ru.png"),
    dialCode: "7",
    trunkPrefix: "8",
    internationalPrefixes: null,
    priority: 146748590,
    areaCodes: null,
  },
  {
    name: "Rwanda",
    iso2: "rw",
    flag: require("@images/flags/rw.png"),
    dialCode: "250",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 12374397,
    areaCodes: null,
  },
  {
    name: "Saint Barthélemy (Saint-Barthélemy)",
    iso2: "bl",
    flag: require("@images/flags/bl.png"),
    dialCode: "590",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1,
    areaCodes: null,
  },
  {
    name: "Saint Helena",
    iso2: "sh",
    flag: require("@images/flags/sh.png"),
    dialCode: "290",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 6000,
    areaCodes: null,
  },
  {
    name: "Saint Kitts and Nevis",
    iso2: "kn",
    flag: require("@images/flags/kn.png"),
    dialCode: "1869",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 52823,
    areaCodes: null,
  },
  {
    name: "Saint Lucia",
    iso2: "lc",
    flag: require("@images/flags/lc.png"),
    dialCode: "1758",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 178696,
    areaCodes: null,
  },
  {
    name: "Saint Martin (Saint-Martin (partie française))",
    iso2: "mf",
    flag: require("@images/flags/mf.png"),
    dialCode: "590",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2,
    areaCodes: null,
  },
  {
    name: "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)",
    iso2: "pm",
    flag: require("@images/flags/pm.png"),
    dialCode: "508",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 5997,
    areaCodes: null,
  },
  {
    name: "Saint Vincent and the Grenadines",
    iso2: "vc",
    flag: require("@images/flags/vc.png"),
    dialCode: "1784",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 110608,
    areaCodes: null,
  },
  {
    name: "Samoa",
    iso2: "ws",
    flag: require("@images/flags/ws.png"),
    dialCode: "685",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 200874,
    areaCodes: null,
  },
  {
    name: "San Marino",
    iso2: "sm",
    flag: require("@images/flags/sm.png"),
    dialCode: "378",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 33553,
    areaCodes: null,
  },
  {
    name: "São Tomé and Príncipe (São Tomé e Príncipe)",
    iso2: "st",
    flag: require("@images/flags/st.png"),
    dialCode: "239",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 210240,
    areaCodes: null,
  },
  {
    name: "Saudi Arabia (‫المملكة العربية السعودية‬‎)",
    iso2: "sa",
    flag: require("@images/flags/sa.png"),
    dialCode: "966",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 34218169,
    areaCodes: null,
  },
  {
    name: "Senegal (Sénégal)",
    iso2: "sn",
    flag: require("@images/flags/sn.png"),
    dialCode: "221",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 16705608,
    areaCodes: null,
  },
  {
    name: "Serbia (Србија)",
    iso2: "rs",
    flag: require("@images/flags/rs.png"),
    dialCode: "381",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 6963764,
    areaCodes: null,
  },
  {
    name: "Seychelles",
    iso2: "sc",
    flag: require("@images/flags/sc.png"),
    dialCode: "248",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 98055,
    areaCodes: null,
  },
  {
    name: "Sierra Leone",
    iso2: "sl",
    flag: require("@images/flags/sl.png"),
    dialCode: "232",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 7901454,
    areaCodes: null,
  },
  {
    name: "Singapore",
    iso2: "sg",
    flag: require("@images/flags/sg.png"),
    dialCode: "65",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 5703600,
    areaCodes: null,
  },
  {
    name: "Sint Maarten",
    iso2: "sx",
    flag: require("@images/flags/sx.png"),
    dialCode: "1721",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 0,
    areaCodes: null,
  },
  {
    name: "Slovakia (Slovensko)",
    iso2: "sk",
    flag: require("@images/flags/sk.png"),
    dialCode: "421",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 5457873,
    areaCodes: null,
  },
  {
    name: "Slovenia (Slovenija)",
    iso2: "si",
    flag: require("@images/flags/si.png"),
    dialCode: "386",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 2095861,
    areaCodes: null,
  },
  {
    name: "Solomon Islands",
    iso2: "sb",
    flag: require("@images/flags/sb.png"),
    dialCode: "677",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 680806,
    areaCodes: null,
  },
  {
    name: "Somalia (Soomaaliya)",
    iso2: "so",
    flag: require("@images/flags/so.png"),
    dialCode: "252",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 15893219,
    areaCodes: null,
  },
  {
    name: "South Africa",
    iso2: "za",
    flag: require("@images/flags/za.png"),
    dialCode: "27",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 58775022,
    areaCodes: null,
  },
  {
    name: "South Korea (대한민국)",
    iso2: "kr",
    flag: require("@images/flags/kr.png"),
    dialCode: "82",
    trunkPrefix: null,
    internationalPrefixes: ["001", "002", "004", "005", "006", "008"],
    priority: 51780579,
    areaCodes: null,
  },
  {
    name: "South Sudan (‫جنوب السودان‬‎)",
    iso2: "ss",
    flag: require("@images/flags/ss.png"),
    dialCode: "211",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 0,
    areaCodes: null,
  },
  {
    name: "Spain (España)",
    iso2: "es",
    flag: require("@images/flags/es.png"),
    dialCode: "34",
    trunkPrefix: null,
    internationalPrefixes: ["00"],
    priority: 47329981,
    areaCodes: null,
  },
  {
    name: "Sri Lanka (ශ්‍රී ලංකාව)",
    iso2: "lk",
    flag: require("@images/flags/lk.png"),
    dialCode: "94",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 21803000,
    areaCodes: null,
  },
  {
    name: "Sudan (‫السودان‬‎)",
    iso2: "sd",
    flag: require("@images/flags/sd.png"),
    dialCode: "249",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 42627655,
    areaCodes: null,
  },
  {
    name: "Suriname",
    iso2: "sr",
    flag: require("@images/flags/sr.png"),
    dialCode: "597",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 581372,
    areaCodes: null,
  },
  {
    name: "Svalbard and Jan Mayen",
    iso2: "sj",
    flag: require("@images/flags/sj.png"),
    dialCode: "47",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1000,
    areaCodes: null,
  },
  {
    name: "Swaziland",
    iso2: "sz",
    flag: require("@images/flags/sz.png"),
    dialCode: "268",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1093238,
    areaCodes: null,
  },
  {
    name: "Sweden (Sverige)",
    iso2: "se",
    flag: require("@images/flags/se.png"),
    dialCode: "46",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 10345449,
    areaCodes: null,
  },
  {
    name: "Switzerland (Schweiz)",
    iso2: "ch",
    flag: require("@images/flags/ch.png"),
    dialCode: "41",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 8619259,
    areaCodes: null,
  },
  {
    name: "Syria (‫سوريا‬‎)",
    iso2: "sy",
    flag: require("@images/flags/sy.png"),
    dialCode: "963",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 17500657,
    areaCodes: null,
  },
  {
    name: "Taiwan (台灣)",
    iso2: "tw",
    flag: require("@images/flags/tw.png"),
    dialCode: "886",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 23596493,
    areaCodes: null,
  },
  {
    name: "Tajikistan",
    iso2: "tj",
    flag: require("@images/flags/tj.png"),
    dialCode: "992",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 9127000,
    areaCodes: null,
  },
  {
    name: "Tanzania",
    iso2: "tz",
    flag: require("@images/flags/tz.png"),
    dialCode: "255",
    trunkPrefix: "0",
    internationalPrefixes: ["000"],
    priority: 57637628,
    areaCodes: null,
  },
  {
    name: "Thailand (ไทย)",
    iso2: "th",
    flag: require("@images/flags/th.png"),
    dialCode: "66",
    trunkPrefix: "0",
    internationalPrefixes: ["001", "002", "003", "004", "005", "006", "007", "008", "009"],
    priority: 66523092,
    areaCodes: null,
  },
  {
    name: "Timor-Leste",
    iso2: "tl",
    flag: require("@images/flags/tl.png"),
    dialCode: "670",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1387149,
    areaCodes: null,
  },
  {
    name: "Togo",
    iso2: "tg",
    flag: require("@images/flags/tg.png"),
    dialCode: "228",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 7538000,
    areaCodes: null,
  },
  {
    name: "Tokelau",
    iso2: "tk",
    flag: require("@images/flags/tk.png"),
    dialCode: "690",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1400,
    areaCodes: null,
  },
  {
    name: "Tonga",
    iso2: "to",
    flag: require("@images/flags/to.png"),
    dialCode: "676",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 100651,
    areaCodes: null,
  },
  {
    name: "Trinidad and Tobago",
    iso2: "tt",
    flag: require("@images/flags/tt.png"),
    dialCode: "1868",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 1363985,
    areaCodes: null,
  },
  {
    name: "Tunisia (‫تونس‬‎)",
    iso2: "tn",
    flag: require("@images/flags/tn.png"),
    dialCode: "216",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 11722038,
    areaCodes: null,
  },
  {
    name: "Turkey (Türkiye)",
    iso2: "tr",
    flag: require("@images/flags/tr.png"),
    dialCode: "90",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 83154997,
    areaCodes: null,
  },
  {
    name: "Turkmenistan",
    iso2: "tm",
    flag: require("@images/flags/tm.png"),
    dialCode: "993",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 6031187,
    areaCodes: null,
  },
  {
    name: "Turks and Caicos Islands",
    iso2: "tc",
    flag: require("@images/flags/tc.png"),
    dialCode: "1649",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 42953,
    areaCodes: null,
  },
  {
    name: "Tuvalu",
    iso2: "tv",
    flag: require("@images/flags/tv.png"),
    dialCode: "688",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 10200,
    areaCodes: null,
  },
  {
    name: "U.S. Virgin Islands",
    iso2: "vi",
    flag: require("@images/flags/vi.png"),
    dialCode: "1340",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 104578,
    areaCodes: null,
  },
  {
    name: "Uganda",
    iso2: "ug",
    flag: require("@images/flags/ug.png"),
    dialCode: "256",
    trunkPrefix: "0",
    internationalPrefixes: ["000"],
    priority: 41590300,
    areaCodes: null,
  },
  {
    name: "Ukraine (Україна)",
    iso2: "ua",
    flag: require("@images/flags/ua.png"),
    dialCode: "380",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 41806221,
    areaCodes: null,
  },
  {
    name: "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)",
    iso2: "ae",
    flag: require("@images/flags/ae.png"),
    dialCode: "971",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 9890400,
    areaCodes: null,
  },
  {
    name: "United Kingdom",
    iso2: "gb",
    flag: require("@images/flags/gb.png"),
    dialCode: "44",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 66796807,
    areaCodes: null,
  },
  {
    name: "United States",
    iso2: "us",
    flag: require("@images/flags/us.png"),
    dialCode: "1",
    trunkPrefix: "1",
    internationalPrefixes: ["011"],
    priority: 329952186,
    areaCodes: null,
  },
  {
    name: "Uruguay",
    iso2: "uy",
    flag: require("@images/flags/uy.png"),
    dialCode: "598",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 3530912,
    areaCodes: null,
  },
  {
    name: "Uzbekistan (Oʻzbekiston)",
    iso2: "uz",
    flag: require("@images/flags/uz.png"),
    dialCode: "998",
    trunkPrefix: "0",
    internationalPrefixes: ["00"],
    priority: 34269199,
    areaCodes: null,
  },
  {
    name: "Vanuatu",
    iso2: "vu",
    flag: require("@images/flags/vu.png"),
    dialCode: "678",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 304500,
    areaCodes: null,
  },
  {
    name: "Vatican City (Città del Vaticano)",
    iso2: "va",
    flag: require("@images/flags/va.png"),
    dialCode: "39",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 825,
    areaCodes: null,
  },
  {
    name: "Venezuela",
    iso2: "ve",
    flag: require("@images/flags/ve.png"),
    dialCode: "58",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 32219521,
    areaCodes: null,
  },
  {
    name: "Vietnam (Việt Nam)",
    iso2: "vn",
    flag: require("@images/flags/vn.png"),
    dialCode: "84",
    trunkPrefix: "0",
    internationalPrefixes: null,
    priority: 96208984,
    areaCodes: null,
  },
  {
    name: "Wallis and Futuna",
    iso2: "wf",
    flag: require("@images/flags/wf.png"),
    dialCode: "681",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 11700,
    areaCodes: null,
  },
  {
    name: "Western Sahara (‫الصحراء الغربية‬‎)",
    iso2: "eh",
    flag: null,
    dialCode: "212",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 582463,
    areaCodes: null,
  },
  {
    name: "Yemen (‫اليمن‬‎)",
    iso2: "ye",
    flag: require("@images/flags/ye.png"),
    dialCode: "967",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 29825968,
    areaCodes: null,
  },
  {
    name: "Zambia",
    iso2: "zm",
    flag: require("@images/flags/zm.png"),
    dialCode: "260",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 17885422,
    areaCodes: null,
  },
  {
    name: "Zimbabwe",
    iso2: "zw",
    flag: require("@images/flags/zw.png"),
    dialCode: "263",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 15159624,
    areaCodes: null,
  },
  {
    name: "Åland Islands",
    iso2: "ax",
    flag: require("@images/flags/ax.png"),
    dialCode: "358",
    trunkPrefix: null,
    internationalPrefixes: null,
    priority: 29981,
    areaCodes: null,
  },
]

type Country = typeof countries[0]

export const countryIndex: Record<string, Country> = {}

for (const country of countries) {
  countryIndex[country.iso2] = country
}
