#!/usr/bin/env bash
set -euxo pipefail

xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug -sdk iphonesimulator build -destination platform="$DEVICE_HOST_PLAT",OS="$DEVICE_HOST_OS",name="$DEVICE_HOST_NAME" -derivedDataPath "$DERIVED_DATA_PATH" ONLY_ACTIVE_ARCH=YES GCC_PREPROCESSOR_DEFINITIONS='$(inherited)' |
	tee ./xcode_build_raw.log |
	bundle exec xcpretty -c

./scripts/ci/upload_sim_app