#!/usr/bin/env bash
set -euxo pipefail


source ./scripts/ci/ci-setup-export-vars

if [ "${LOCAL_BRANCH}" != "beta-ios" ] && [ "${LOCAL_BRANCH}" != "app_store_submission" ]; then
	./scripts/ci/build-for-tests-ios
else
	echo "Skipping test build on beta deploy."
fi
