#!/usr/bin/env bash
set -exo pipefail


source ./scripts/ci/ci-setup-export-vars

if [ "${LOCAL_BRANCH}" != "beta-android" ] && [ "${LOCAL_BRANCH}" != "app_store_submission" ]; then
	./scripts/ci/test-android
else
	echo "Skipping test run on beta deploy."
fi
