#!/usr/bin/env bash
set -euxo pipefail

xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug test -sdk iphonesimulator -destination platform="$DEVICE_HOST_PLAT",OS="$DEVICE_HOST_OS",name="$DEVICE_HOST_NAME" -derivedDataPath "$DERIVED_DATA_PATH" |
	tee ./xcode_test_raw.log |
	bundle exec xcpretty -c --test --report junit --output ./test-results.xml
