#!/usr/bin/env bash
set -euxo pipefail


if test ${CI:-false} = true
then
  ./scripts/setup/setup-distribute
fi

aws s3 cp s3://artsy-citadel/eigen/google-services.json android/app/google-services.json
aws s3 cp s3://artsy-citadel/eigen/GoogleService-Info.plist ios/Artsy/GoogleService-Info.plist
aws s3 cp s3://artsy-citadel/eigen/AppCenter-Config.plist ios/Artsy/AppCenter-Config.plist


./scripts/setup/download-fonts
