#!/usr/bin/env bash

set -euxo pipefail

# Install vendored CLI tool dependencies
echo "Installing bin toolchain dependencies..."
cd bin
yarn --cwd bin install --immutable
cd ..

echo "✅ Bin dependencies installed successfully."