#!/usr/bin/env bash
set -euxo pipefail


aws s3 cp s3://artsy-citadel/eigen/.env.shared .env.shared
aws s3 cp s3://artsy-citadel/eigen/.env.shared .env
aws s3 cp s3://artsy-citadel/eigen/.env.releases .env.releases

cp metaflags.example.json metaflags.json
