#!/usr/bin/env bash
set -exo pipefail

if ! which aws;
then
  echo "installing aws"

  # install awscli
  if [ "$(uname)" == "Darwin" ]; then # MacOS
    curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
    sudo installer -pkg AWSCLIV2.pkg -target /
    # Remove the installer so fastlane deliver doesn't auto-detect it via Dir["*.pkg"]
    # and force the delivery platform to 'osx'. See detect_values.rb#find_platform.
    rm -f AWSCLIV2.pkg
  else # Assume Linux
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip -o -qq awscliv2.zip
    sudo ./aws/install
  fi
  # ensure awscli is installed
  # and version details
  which aws
  aws --version

  # configure awscli
  mkdir -p ~/.aws
  touch ~/.aws/config
  echo "[default]" >> ~/.aws/config
  echo "region = us-east-1" >> ~/.aws/config
  echo "output = json" >> ~/.aws/config
else
  echo "aws already installed"
fi