#!/usr/bin/env bash
set -exo pipefail

# brew not working in docker/linux in circleci
# brew update
# brew tap getsentry/tools
# brew install sentry-cli
if ! which sentry-cli;
then
  echo "installing sentry-cli"
  curl -sL https://sentry.io/get-cli/ | bash
else
  echo "sentry-cli already installed"
fi

./scripts/setup/setup-awscli

./scripts/setup/download-assets-android
