# frozen_string_literal: true

source 'https://cdn.cocoapods.org/'
source 'https://github.com/artsy/Specs.git'

require 'dotenv'
Dotenv.load('../.env.shared')

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip


project 'Artsy.xcodeproj'
platform :ios, min_ios_version_supported
inhibit_all_warnings! # ignore all warnings from all pods

prepare_react_native_project!

$ReactNativeMapboxGLIOSVersion = '~> 6.4'

plugin 'cocoapods-patch'

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


def check_for_existing_netrc_file
  mapbox_token = ENV['MAPBOX_DOWNLOAD_TOKEN']
  if !mapbox_token || mapbox_token.length <= 1
    raise "You need a MAPBOX_DOWNLOAD_TOKEN in your .env.shared file.\nIf you work at artsy, check 1password.\nOtherwise create your own in the mapbox dashboard. https://docs.mapbox.com/ios/maps/guides/install"
  end
  # mapbox needs credentials in `~/.netrc`, so we put them there and then remove them in post-pod-install.rb
  $netrc_path = File.expand_path('~/.netrc')
  user_already_had_a_netrc_file = File.exists?($netrc_path)
  if user_already_had_a_netrc_file
    system("touch .i-had-a-netrc-file")
  else
    system("rm -rf .i-had-a-netrc-file")
  end
end

def add_mapbox_creds
  File.open($netrc_path, 'a+', 0600) { |f|
    f.write("""machine api.mapbox.com
login mapbox
password #{ENV['MAPBOX_DOWNLOAD_TOKEN']}
""")
  }
end

check_for_existing_netrc_file
add_mapbox_creds

pre_install do |installer|
  $RNMBGL.pre_install(installer)
end


target 'Artsy' do
  # Flags change depending on the env values.
  flags = get_default_flags()

  if ENV['CI']
    config = use_native_modules!(packages_to_skip: ['react-native-flipper'])
  else
    config = use_native_modules!
  end


  use_react_native!(
    :path => config[:reactNativePath],
    :production => ENV['CIRCLE_BUILD_NUM'],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Networking
  pod 'AFNetworking', '2.7.0', subspecs: %w[NSURLSession NSURLConnection]
  pod 'AFNetworkActivityLogger'
  pod 'SDWebImage', '5.11.1'
  pod 'INTUAnimationEngine'

  # Core
  pod 'CocoaLumberjack', '3.7.2'
  pod 'FLKAutoLayout', git: 'https://github.com/artsy/FLKAutoLayout.git', branch: 'v1'
  pod 'FXBlurView', '1.6.4'
  pod 'ISO8601DateFormatter', git: 'https://github.com/artsy/iso-8601-date-formatter'
  pod 'JSDecoupledAppDelegate'
  pod 'Mantle', '1.5.6'
  pod 'MMMarkdown', '0.4'
  pod 'UICKeyChainStore'
  pod 'MARKRangeSlider'

  # Core owned by Artsy
  pod 'ORStackView', '2.0.3'
  pod 'UIView+BooleanAnimations'
  pod 'Aerodramus', '2.0.0'

  # Language Enhancements
  pod 'MultiDelegate'
  pod 'ObjectiveSugar'

  # For Stripe integration with Emission. Using a fork for this issue: https://github.com/tipsi/tipsi-stripe/issues/408
  pod 'Pulley', git: 'https://github.com/artsy/Pulley.git', branch: 'master'

  # Facebook
  pod 'FBSDKCoreKit', '~> 16.3.1'
  pod 'FBSDKLoginKit', '~> 16.3.1'
  pod 'FBSDKShareKit', '~> 16.3.1'

  # Google & Firebase
  pod 'GoogleSignIn', '5.0.2'
  pod 'Firebase/Auth', '8.1.0'

  # Analytics
  pod 'Segment-Appboy'

  # Swift pods 🎉
  pod 'Then', '2.3.0'
  pod 'Interstellar/Core', git: 'https://github.com/artsy/Interstellar.git', branch: 'observable-unsubscribe'
  pod 'Starscream', '3.0.4'
  pod 'SwiftyJSON', '4.0.0'

  # Used in Live Auctions to hold user-state
  pod 'JWTDecode', '2.0.0'

  target 'ArtsyTests' do
    inherit! :search_paths

    pod 'OHHTTPStubs', '3.1.2'
    pod 'XCTest+OHHTTPStubSuiteCleanUp'
    pod 'Specta'
    pod 'Expecta', '1.0.6'
    pod 'Expecta+Snapshots', '3.1.1'
    pod 'OCMock'
    pod 'Forgeries/Mocks'

    # Swift pods 🎉
    pod 'Quick', '2.0.0'
    pod 'Nimble', '7.3.4'
    pod 'Nimble-Snapshots', '6.3.0'
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'Flipper'
        file_path = 'Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h'
        contents = File.read(file_path)
        unless contents.include?('#include <functional>')
          File.open(file_path, 'w') do |file|
            file.puts('#include <functional>')
            file.puts(contents)
          end
        end
      end
    end

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    if !ENV['CI']
      flipper_post_install(installer)
    end

    $RNMBGL.post_install(installer)

    # For now Nimble Snapshots needs to stay at Swift 4.0
    swift4 = ['Nimble-Snapshots']
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0' if swift4.include?(target.name)
      end
    end

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
  end
end
