# frozen_string_literal: true

source 'https://cdn.cocoapods.org/'
source 'https://github.com/artsy/Specs.git'

require 'dotenv'
Dotenv.load('../.env.shared')

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


project 'Artsy.xcodeproj'
platform :ios, '14.0'
inhibit_all_warnings! # ignore all warnings from all pods


$ReactNativeMapboxGLIOSVersion = '~> 6.4'


def check_for_existing_netrc_file
  mapbox_token = ENV['MAPBOX_DOWNLOAD_TOKEN']
  if !mapbox_token || mapbox_token.length <= 1
    raise "You need a MAPBOX_DOWNLOAD_TOKEN in your .env.shared file.\nIf you work at artsy, check 1password.\nOtherwise create your own in the mapbox dashboard. https://docs.mapbox.com/ios/maps/guides/install"
  end
  # mapbox needs credentials in `~/.netrc`, so we put them there and then remove them in post-pod-install.rb
  $netrc_path = File.expand_path('~/.netrc')
  user_already_had_a_netrc_file = File.exists?($netrc_path)
  if user_already_had_a_netrc_file
    system("touch .i-had-a-netrc-file")
  else
    system("rm -rf .i-had-a-netrc-file")
  end
end

def add_mapbox_creds
  File.open($netrc_path, 'a+', 0600) { |f|
    f.write("""machine api.mapbox.com
login mapbox
password #{ENV['MAPBOX_DOWNLOAD_TOKEN']}
""")
  }
end

check_for_existing_netrc_file
add_mapbox_creds

pre_install do |installer|
  $RNMBGL.pre_install(installer)
end


target 'Artsy' do
  if ENV['CI']
    config = use_native_modules!(packages_to_skip: ['react-native-flipper'])
  else
    config = use_native_modules!
  end
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
    :production => ENV['CIRCLE_BUILD_NUM'],
  )

  # Networking
  pod 'AFNetworking', '2.7.0', subspecs: %w[Reachability Serialization Security NSURLSession NSURLConnection]
  pod 'AFOAuth1Client', git: 'https://github.com/artsy/AFOAuth1Client.git', tag: '0.4.0-subspec-fix'
  pod 'AFNetworkActivityLogger'
  pod 'SDWebImage', '5.11.1'
  pod 'INTUAnimationEngine'

  # Core
  pod 'ARGenericTableViewController', git: 'https://github.com/artsy/ARGenericTableViewController.git'
  pod 'CocoaLumberjack', '3.7.2'
  pod 'FLKAutoLayout', git: 'https://github.com/artsy/FLKAutoLayout.git', branch: 'v1'
  pod 'FXBlurView', '1.6.4'
  pod 'ISO8601DateFormatter', git: 'https://github.com/artsy/iso-8601-date-formatter'
  pod 'JSDecoupledAppDelegate'
  pod 'Mantle', '1.5.6'
  pod 'MMMarkdown', '0.4'
  pod 'UICKeyChainStore'
  pod 'MARKRangeSlider'
  pod 'EDColor', '1.0.1'

  # Core owned by Artsy
  pod 'ORStackView', '2.0.3'
  pod 'UIView+BooleanAnimations'
  pod 'Aerodramus', '2.0.0'

  # Language Enhancements
  pod 'MultiDelegate'
  pod 'ObjectiveSugar'

  # For Stripe integration with Emission. Using a fork for this issue: https://github.com/tipsi/tipsi-stripe/issues/408
  pod 'Pulley', git: 'https://github.com/artsy/Pulley.git', branch: 'master'

  # Facebook
  pod 'FBSDKCoreKit', '15.0.0'
  pod 'FBSDKLoginKit', '15.0.0'
  pod 'FBSDKShareKit', '15.0.0'

  # Google & Firebase
  pod 'GoogleSignIn', '5.0.2'
  pod 'Firebase/Auth', '8.1.0'

  # Analytics
  pod 'Segment-Appboy'

  # Swift pods 🎉
  pod 'Then', '2.3.0'
  pod 'Interstellar/Core', git: 'https://github.com/artsy/Interstellar.git', branch: 'observable-unsubscribe'
  pod 'Starscream', '3.0.4'
  pod 'SwiftyJSON', '4.0.0'

  # Used in Live Auctions to hold user-state
  pod 'JWTDecode', '2.0.0'

  target 'ArtsyTests' do
    inherit! :search_paths

    pod 'OHHTTPStubs', '3.1.2'
    pod 'XCTest+OHHTTPStubSuiteCleanUp'
    pod 'Specta'
    pod 'Expecta', '1.0.6'
    pod 'Expecta+Snapshots', '3.1.1'
    pod 'OCMock'
    pod 'Forgeries/Mocks'

    # Swift pods 🎉
    pod 'Quick', '2.0.0'
    pod 'Nimble', '7.3.4'
    pod 'Nimble-Snapshots', '6.3.0'
  end

  # Enables Flipper but not for CI.
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  if !ENV['CI']
    use_flipper!({ 'Flipper' => '0.189.0' })
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    if !ENV['CI']
      flipper_post_install(installer)
    end

    $RNMBGL.post_install(installer)

    # For now Nimble Snapshots needs to stay at Swift 4.0
    swift4 = ['Nimble-Snapshots']
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0' if swift4.include?(target.name)
      end
    end

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end

    # TODO:
    # * ORStackView: Move Laura's changes into master and update
    # * Send PRs for the rest
    %w[
      Pods/ORStackView/Classes/ios/ORStackView.h
    ].flat_map { |x| Dir.glob(x) }.each do |header|
      system("chmod +w #{header}")
      addition = "#import <UIKit/UIKit.h>\n"
      contents = File.read(header)
      next if contents.include?(addition)

      File.open(header, 'w') do |file|
        file.puts addition
        file.puts contents
      end
    end

    # TODO: Might be nice to have a `cocoapods-patch` plugin that applies patches like `patch-package` does for npm.
    %w[
      Pods/Nimble/Sources/NimbleObjectiveC
      Pods/Nimble-Snapshots
      Pods/Quick/Sources/QuickObjectiveC
    ].flat_map { |x| Dir.glob(File.join(x, '**/*.{h,m}')) }.each do |header|
      system("chmod +w #{header}")
      contents = File.read(header)
      patched = contents.sub(%r{["<]\w+/(\w+-Swift\.h)[">]}, '"\1"')
      File.write(header, patched) if Regexp.last_match
    end
  end
end
