export default {
  de: {
    "component.artist.articles.section.title": "Ausgewählte Artikel",
    "component.artist.artistabout.artistseries.header": "Top-Künstler-Reihe",
    "component.artist.artistaboutshows.featuring": "Shows mit {artistName}",
    "component.artist.artistaboutshows.button": "Alle vergangenen Sendungen ansehen",
    "component.artist.artistartworks.artistcollectionsrails.section.title": "Ikonische Sammlungen",
    "component.artist.artistartworks.artistnotableworksrails.section.title": "Nennenswerte Werke",
    "component.artist.artistartworks.createsavedsearchmodal.popover.title":
      "Ihre Benachrichtigung wurde erstellt.",
    "component.artist.artistartworks.createsavedsearchmodal.popover.message":
      "Bearbeiten Sie Ihre Benachrichtigungen in Ihrem Profil in den Einstellungen.",
    "component.artist.artistartworks.savedsearchbuttonv2.title": "Benachrichtigung erstellen",
    "component.artist.artistinsights.artistinsights.section.title": "Auktionsergebnisse filtern",
    "component.artist.artistinsights.artistinsightsauctionresults.renderauctionresultsmodal.text1":
      "Diese Auktionsergebnisse führen Verkaufsdaten von Top-Auktionshäusern auf der ganzen Welt zusammen, darunter Christie’s, Sotheby’s, Phillips und Bonhams. Die Ergebnisse werden täglich aktualisiert.",
    "component.artist.artistinsights.artistinsightsauctionresults.renderauctionresultsmodal.text2":
      "Bitte beachten Sie, dass der Verkaufspreis den Zuschlagspreis und das Käuferaufgeld sowie alle anderen zusätzlichen Gebühren (z. B. Folgerechte des Künstlers) enthält.",
    "component.artist.artistinsights.artistinsightsauctionresults.infobutton.title":
      "Auktionsergebnisse",
    "component.artist.artistinsights.artistinsightsauctionresults.sortmode.sortdescription":
      "Sortiert nach {sortDescription}",
    "component.artist.artistinsights.artistinsightsauctionresults.resultsText": "Ergebnis",
    "component.artist.artistinsights.artistinsightsauctionresults.resultsTextPlural": "Ergebnisse",
    "component.artist.artistinsights.marketstats.renderinfomodal.text1":
      "Die folgenden Datenpunkte geben einen Überblick über den Auktionsmarkt eines Künstlers für ein bestimmtes Objekt (z. B. Fotografie, Gemälde) in den letzten 36 Monaten.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text2":
      "Diese Marktsignale führen Daten von Top-Auktionshäusern auf der ganzen Welt zusammen, darunter Christie’s, Sotheby’s, Phillips und Bonhams.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text3":
      "Bitte beachten Sie, dass in diesem Datensatz der Verkaufspreis den Zuschlagspreis und das Käuferaufgeld sowie alle anderen zusätzlichen Gebühren (z. B. Folgerechte des Künstlers) enthält. Der Datensatz enthält nur Werke im Wert von über 1.000 US-Dollar.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text4":
      "Durchschnittliche jährliche verkaufte Lose",
    "component.artist.artistinsights.marketstats.renderinfomodal.text5":
      "Die durchschnittliche Anzahl der Lose, die in den letzten 36 Monaten pro Jahr bei einer Auktion verkauft wurden.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text6": "Durchverkaufsrate",
    "component.artist.artistinsights.marketstats.renderinfomodal.text7":
      "Der Prozentsatz der Lose in Auktionen, die in den letzten 36 Monaten verkauft wurden.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text8":
      "Durchschnittlicher Verkaufspreis",
    "component.artist.artistinsights.marketstats.renderinfomodal.text9":
      "Der durchschnittliche Verkaufspreis der Lose, die in den letzten 36 Monaten bei einer Auktion verkauft wurden.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text10":
      "Verkaufspreis über Schätzung",
    "component.artist.artistinsights.marketstats.renderinfomodal.text11":
      "Die durchschnittliche prozentuale Differenz des Verkaufspreises gegenüber dem mittleren Schätzpreis (dem Mittelpunkt des vom Auktionshaus vor der Auktion festgelegten unteren und oberen Schätzpreises) für Lose, die in den letzten 36 Monaten auf einer Auktion verkauft wurden.",
    "component.artist.artistinsights.marketstats.infobutton.title": "Marktsignale",
    "component.artist.artistinsights.marketstats.averagetext":
      "Durchschnittswerte der letzten 36 Monate",
    "component.artist.artistinsights.marketstats.select.title": "Mittel auswählen",
    "component.artist.artistinsights.marketstats.annuallotssold": "Jährlich verkaufte Lose",
    "component.artist.artistinsights.marketstats.sellthroughrate": "Durchverkaufsrate",
    "component.artist.artistinsights.marketstats.saleprice": "Verkaufspreis",
    "component.artist.artistinsights.marketstats.salepriceoverestimate":
      "Verkaufspreis über Schätzung",
    "component.artist.artistConsignButton.headline.default":
      "Verkaufen Sie Kunst aus Ihrer Sammlung",
    "component.artist.artistConsignButton.headline.inMicrofunnel": "Verkaufen Sie Ihren {name}",
    "component.artist.artistConsignButton.consignText": "Bei Artsy einliefern",
    "component.artist.artistHeader.workText": "Kunstwerk",
    "component.artist.artistHeader.workTextPlural": "Kunstwerke",
    "component.artist.artistHeader.followerText": "Anhänger",
    "component.artist.artistHeader.followerTextPlural": "Anhänger",
    "component.artist.biography.section.title": "Biografie",
    "component.artworkGrids.artworkGridItem.lotText": "Haufen {lotLabel}",
    "component.artworkGrids.artworkGridItem.soldForText": "Verkauft für {realizedPrize}",
    "component.artworkGrids.artworkGridItem.biddingClosedText": "Ausschreibung geschlossen",
    "component.artworkGrids.artworkGridItem.bidderPosition.smallTileText": "{currentBid} (Gebot)",
    "component.artworkGrids.artworkGridItem.bidderPosition.defaultText:":
      "{currentBid} (Startgebot)",
    "component.artworkGrids.artworkGridItem.bidderPosition.bidSingular": "1 Gebot",
    "component.artworkGrids.artworkGridItem.bidderPosition.bidPlural": "{bidderPositions} Gebote",
    "component.artworkGrids.artworkGridItem.saleMessage": "Preis auf Anfrage",
    "component.artworkGrids.artworksFilterHeader.title": "Sortieren & Filtern",
    "component.artworkGrids.filteredArtworkGridZeroState.zeroStateMessage":
      "Keine Ergebnisse gefunden\nBitte versuchen Sie es mit einer anderen Suche.",
    "component.artworkGrids.filteredArtworkGridZeroState.clearButton": "Filter löschen",
    "component.artworkRail.artworkRailCard.lotText": "Haufen {lotLabel}",
    "component.entityList.andText": " und ",
    "component.entityList.othersText": "weitere",
    "component.headerArtworksFilter.headerArtworksFilter.title": "Sortieren & Filtern",
    "component.headerArtworksFilter.headerArtworksFilter.totalWorksShown":
      "{total} Kunstwerke werden angezeigt",
    "component.customShareSheet.share": "Teilen",
    "component.menuItem.beta": "Beta",
    "component.searchInput.cancel": "Abbrechen",
    "component.sectionTitle.rightButton.viewAll": "Alle ansehen",
    "component.photos.doneText": "Fertig",
    "component.relatedArtists.relatedArtists.section.title": "Verwandte Künstler",
    "component.relatedArtists.relatedArtist.workText": "Kunstwerk",
    "component.relatedArtists.relatedArtist.workTextPlural": "Kunstwerke",
    "component.relatedArtists.relatedArtist.forSaleText": "zu verkaufen",
    "component.show.showArtistsPreview.artists": "Künstler",
    "component.show.showArtistsPreview.caretButton": "Alle Künstler von {length} anzeigen",
    "component.show.showArtworksPreview.caretButton": "Alle Werke von {length} anzeigen",
    "container.inbox.inquiries": "Anfragen",
    "container.inbox.bids": "Gebote",
    "container.inquiry.sendButton.sending": "Senden...",
    "container.inquiry.sendButton.send": "Schicken",
    "container.inquiry.cancel": "Abbrechen",
    "container.worksForYou.zeroState.title": "Du folgst noch keinem Künstler",
    "container.worksForYou.zeroState.subtitle":
      "Folgen Sie Künstlern, um neue Werke zu sehen, die zu Artsy hinzugefügt wurden.",
    "scene.about.about": "Über",
    "scene.about.termsOfUse": "Nutzungsbedingungen",
    "scene.about.privacyPolicy": "Datenschutz-Bestimmungen",
    "scene.about.conditionsOfSale": "Verkaufsbedingungen",
    "scene.articles.articlesList.title": "Marktnachrichten",
    "scene.artist.tabs.overview": "Überblick",
    "scene.artist.tabs.artworks": "Kunstwerke",
    "scene.artist.tabs.insights": "Einblicke",
    "scene.artist.tabs.noArtworks":
      "TDerzeit sind keine Werke des Künstlers verfügbar. Folgen Sie, um Benachrichtigungen zu erhalten, wenn neue Werke hinzugefügt werden.",
    "scene.artist.popover.title": "Entschuldigung, ein Fehler ist aufgetreten",
    "scene.artist.popover.message": "Gespeicherte Suchkriterien konnten nicht abgerufen werden",
    "scene.artistArticles.artistArticles.title": "{name}-Artikel",
    "scene.artistSeries.artistSeries.moreSeries": "Weitere Serien dieses Künstlers",
    "scene.artistSeries.artistSeries.totalWorksShown": "{total} Kunstwerke werden angezeigt",
    "scene.artistSeries.artistSeriesFullArtistSeries.header": "Künstler-Reihe",
    "scene.artistSeries.artistSeriesMeta.follow": "Folgen",
    "scene.artistSeries.artistSeriesMeta.following": "Folgend",
    "scene.artistSeries.artistSeriesMoreSeries.viewAll": "Alle {totalCount} anzeigen",
    "scene.artistShows.artistShows2.pastShows": "Vergangene Shows",
    "scene.artwork.components.aboutArtist.aboutTheArtist": "Über den Künstler",
    "scene.artwork.components.aboutArtist.aboutTheArtists": "Über die Künstler",
    "scene.artwork.components.aboutWork.aboutTheWork": "Über das Kunstwerk",
    "scene.artwork.components.aboutWork.fromArtsySpecialist": "Vom Artsy-Spezialisten:",
    "scene.artwork.components.artworkActions.computedTitleWithNames":
      "{title} von {names} auf Artsy",
    "scene.artwork.components.artworkActions.computedTitle": "{title} auf Artsy",
    "scene.artwork.components.artworkActions.watchLot": "Los ansehen",
    "scene.artwork.components.artworkActions.save": "Speichern",
    "scene.artwork.components.artworkActions.saved": "Gerettet",
    "scene.artwork.components.artworkActions.viewInRoom": "Blick ins Zimmer",
    "scene.artwork.components.artworkActions.share": "Teilen",
    "scene.artwork.components.artworkDetails.listItems.medium": "Medium",
    "scene.artwork.components.artworkDetails.listItems.condition": "Zustand",
    "scene.artwork.components.artworkDetails.listItems.signature": "Unterschrift",
    "scene.artwork.components.artworkDetails.listItems.certificateOfAuthenticity":
      "Echtheitsbescheinigung",
    "scene.artwork.components.artworkDetails.listItems.frame": "Rahmen",
    "scene.artwork.components.artworkDetails.listItems.series": "Serie",
    "scene.artwork.components.artworkDetails.listItems.publisher": "Herausgeber",
    "scene.artwork.components.artworkDetails.listItems.manufacturer": "Hersteller",
    "scene.artwork.components.artworkDetails.listItems.imageRights": "Bildrechte",
    "scene.artwork.components.artworkDetails.artworkDetails": "Kunstwerkdetails",
    "scene.artwork.components.artworkHistory.sections.provenance": "Herkunft",
    "scene.artwork.components.artworkHistory.sections.exhibitionHistory": "Ausstellungsgeschichte",
    "scene.artwork.components.artworkHistory.sections.literature": "Literaturverzeichnis",
    "scene.artwork.components.artworkSeriesRails.section.title": "Mehr aus dieser Serie",
    "scene.artwork.components.artworkTombstone.more": "mehr",
    "scene.artwork.components.artworkTombstone.lot": "Partie {lotLabel}",
    "scene.artwork.components.artworkTombstone.estimatedValue": "Geschätzter Wert: {estimate}",
    "scene.artwork.components.auctionPrice.bidsCountSingular": "1 Gebot",
    "scene.artwork.components.auctionPrice.bidsCountPlural": "{bidsCount} Gebote",
    "scene.artwork.components.auctionPrice.biddingClosed": "Ausschreibung geschlossen",
    "scene.artwork.components.auctionPrice.currentBid": "Aktuelles Gebot",
    "scene.artwork.components.auctionPrice.startingBid": "Startgebot",
    "scene.artwork.components.auctionPrice.yourMaxBid": "Ihr Maximum: {myMaxBid}",
    "scene.artwork.components.auctionPrice.auctionHas": "Diese Auktion hat eine ",
    "scene.artwork.components.auctionPrice.buyersPremium": "Käuferprovision",
    "scene.artwork.components.auctionPrice.shipping":
      "Versand, Steuern und zusätzliche Gebühren können anfallen.",
    "scene.artwork.components.commercialEditionSetInformation.editionSize": "Auflagengröße",
    "scene.artwork.components.commercialInformation.saleMessage": "Preis auf Anfrage",
    "scene.artwork.components.commercialInformation.newSaleMessage.biddingClosed":
      "Ausschreibung geschlossen",
    "scene.artwork.components.commercialInformation.newSaleMessage.forSale": "Zu verkaufen",
    "scene.artwork.components.CommercialPartnerInformation.taxes":
      "An der Kasse können Steuern anfallen. ",
    "scene.artwork.components.CommercialPartnerInformation.learnMore": "Mehr erfahren.",
    "scene.artwork.components.CommercialPartnerInformation.shipsFrom":
      "Versand aus {shippingOrigin}",
    "scene.artwork.components.contextCard.header.inAuction": "Bei Auktion",
    "scene.artwork.components.contextCard.header.inFair": "Im Fair",
    "scene.artwork.components.contextCard.header.inShow": "Im Schaufenster",
    "scene.artwork.components.followArtistLink.followButtonText.following": "Folgend",
    "scene.artwork.components.followArtistLink.followButtonText.follow": "Folgen",
    "scene.artwork.components.partnerCard.partnerTypeDisplayText.gallery": "Galerie",
    "scene.artwork.components.partnerCard.partnerTypeDisplayText.institution": "Institution",
    "scene.artwork.components.requestConditionReport.presentErrorModal.message":
      "Bei der Verarbeitung Ihrer Anfrage ist ein Problem aufgetreten. Bitte versuche es erneut.",
    "scene.artwork.components.requestConditionReport.requestReport": "Zustandsbericht anfordern",
    "scene.artwork.components.requestConditionReport.modal.error.headerText":
      "Ein Fehler ist aufgetreten",
    "scene.artwork.components.requestConditionReport.modal.headerText":
      "Zustandsbericht angefordert",
    "scene.artwork.components.requestConditionReport.modal.detailText":
      "Wir haben ihre Anfrage erhalten.\nDer Zustandsbericht wird an gesendet {email}.\nBei Fragen kontaktieren Sie Specialist@artsy.net.",
    "scene.home.newWorksForYou.title": "Neue Kunstwerke für Sie",
    "scene.home.yourActiveBids.title": "Ihre aktiven Gebote",
    "scene.home.auctionLotsForYouEndingSoon.title": "Auktionslose für Sie, die bald enden",
    "scene.home.auctions.title": "Auktionen",
    "scene.home.auctions.subtitle": "Entdecken und bieten Sie auf Werke für Sie",
    "scene.home.auctionResultsForArtistsYouFollow.title":
      "Auktionsergebnisse für Künstler, denen Sie folgen",
    "scene.home.marketNews.title": "Marktnachrichten",
    "scene.home.recommendedArtists.title": "Empfohlene Künstler",
    "scene.home.showsForYou.title": "Shows für Sie",
    "scene.home.trove.title": "Trove",
    "scene.home.viewingRooms.title": "Besichtigungsräume",
    "scene.home.collections.title": "Sammlungen",
    "scene.home.collections.subtitle": "Die neuesten Werke, kuratiert von Artsy",
    "scene.home.artworkRecommendations.title": "Artwork-Empfehlungen",
    "scene.home.featuredFairs.title": "Ausgewählte Stände",
    "scene.home.featuredFairs.subtitle": "Sehen Sie Kunstwerke auf Top-Kunstmessen",
    "scene.home.popularArtists.title": "Beliebte Künstler",
    "scene.home.recentlyViewed.title": "zuletzt angesehen",
    "scene.home.similarToWorks.title": "Ähnlich wie Kunstwerke, die Sie angesehen haben",
    "scene.myCollection.myCollection.button.addWorks": "Kunstwerke hinzufügen",
    "scene.myCollection.myCollectionArtwork.zeroState.title": "Ihre Kunstsammlung in der Tasche.",
    "scene.myCollection.myCollectionArtwork.zeroState.subtitle":
      "Behalten Sie den Überblick über Ihre Sammlung an einem Ort und erhalten Sie Markteinblicke",
    "scene.myCollection.myCollectionArtwork.zeroState.button": "Kunstwerke hinzufügen",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.tabs.collection": "Meine Sammlung",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.tabs.savedWorks":
      "Gespeicherte Kunstwerke",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.myProfileHeader.memberSince":
      "Mitglied seit {year}",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.myProfileHeader.settings":
      "Einstellungen",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.myProfileHeader.editProfile":
      "Profil bearbeiten",
    "scene.search.search.searchInputContainer.placeholder":
      "Suchen Sie nach Künstlern, Kunstwerken, Galerien usw",
    "scene.search.recentSearches.section.title": "Letzte Suchen",
    "scene.search.recentSearches.noRecentSearches": "Wir speichern Ihre letzten Suchen hier",
    "palette.elements.button.followButton.follow": "Folgen",
    "palette.elements.button.followButton.following": "Folgend",
  },
  en: {
    "component.articles.section.title": "Featured Articles",
    "component.artist.artistabout.artistseries.header": "Top Artist Series",
    "component.artist.artistaboutshows.featuring": "Shows Featuring {artistName}",
    "component.artist.artistaboutshows.button": "See all past shows",
    "component.artist.artistartworks.artistcollectionsrails.section.title": "Iconic Collections",
    "component.artist.artistartworks.artistnotableworksrails.section.title": "Notable Works",
    "component.artist.artistartworks.createsavedsearchmodal.popover.title":
      "Your alert has been created.",
    "component.artist.artistartworks.createsavedsearchmodal.popover.message":
      "Edit your alerts in your profile, in Settings.",
    "component.artist.artistartworks.savedsearchbuttonv2.title": "Create Alert",
    "component.artist.artistinsights.artistinsights.section.title": "Filter auction results",
    "component.artist.artistinsights.artistinsightsauctionresults.renderauctionresultsmodal.text1":
      "These auction results bring together sale data from top auction houses around the world, including Christie’s, Sotheby’s, Phillips and Bonhams. Results are updated daily.",
    "component.artist.artistinsights.artistinsightsauctionresults.renderauctionresultsmodal.text2":
      "Please note that the sale price includes the hammer price and buyer’s premium, as well as any other additional fees (e.g., Artist’s Resale Rights).",
    "component.artist.artistinsights.artistinsightsauctionresults.infobutton.title":
      "Auction Results",
    "component.artist.artistinsights.artistinsightsauctionresults.sortmode.sortdescription":
      "Sorted by {sortDescription}",
    "component.artist.artistinsights.artistinsightsauctionresults.resultsText": "result",
    "component.artist.artistinsights.artistinsightsauctionresults.resultsTextPlural": "results",
    "component.artist.artistinsights.marketstats.renderinfomodal.text1":
      "The following data points provide an overview of an artist’s auction market for a specific (e.g., photography, painting) over the past 36 months..",
    "component.artist.artistinsights.marketstats.renderinfomodal.text2":
      "These market signals bring together data from top auction houses around the world, including Christie’s, Sotheby’s, Phillips and Bonhams.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text3":
      "In this data set, please note that the sale price includes the hammer price and buyer’s premium, as well as any other additional fees (e.g., Artist’s Resale Rights). The data set only includes works valued over $1,000.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text4": "Average yearly lots sold",
    "component.artist.artistinsights.marketstats.renderinfomodal.text5":
      "The average number of lots sold per year at auction over the past 36 months.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text6": "Sell-through rate",
    "component.artist.artistinsights.marketstats.renderinfomodal.text7":
      "The percentage of lots in auctions that sold over the past 36 months.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text8": "Average sale price",
    "component.artist.artistinsights.marketstats.renderinfomodal.text9":
      "The average sale price of lots sold at auction over the past 36 months.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text10":
      "Sale price over estimate",
    "component.artist.artistinsights.marketstats.renderinfomodal.text11":
      "The average percentage difference of the sale price over the mid-estimate (the midpoint of the low and high estimates set by the auction house before the auction takes place) for lots sold at auction over the past 36 months.",
    "component.artist.artistinsights.marketstats.infobutton.title": "Market Signals",
    "component.artist.artistinsights.marketstats.averagetext": "Averages over last 36 months",
    "component.artist.artistinsights.marketstats.select.title": "Select medium",
    "component.artist.artistinsights.marketstats.annuallotssold": "Yearly lots sold",
    "component.artist.artistinsights.marketstats.sellthroughrate": "Sell-through rate",
    "component.artist.artistinsights.marketstats.saleprice": "Sale price",
    "component.artist.artistinsights.marketstats.salepriceoverestimate": "Sale price over estimate",
    "component.artist.artistConsignButton.headline.default": "Sell art from your collection",
    "component.artist.artistConsignButton.headline.inMicrofunnel": "Sell your {name}",
    "component.artist.artistConsignButton.consignText": "Consign with Artsy",
    "component.artist.artistHeader.workText": "work",
    "component.artist.artistHeader.workTextPlural": "works",
    "component.artist.artistHeader.followerText": "follower",
    "component.artist.artistHeader.followerTextPlural": "followers",
    "component.artist.biography.section.title": "Biography",
    "component.artworkGrids.artworkGridItem.lotText": "Lot {lotLabel}",
    "component.artworkGrids.artworkGridItem.soldForText": "Sold for {realizedPrize}",
    "component.artworkGrids.artworkGridItem.biddingClosedText": "Bidding closed",
    "component.artworkGrids.artworkGridItem.bidderPosition.smallTileText": "{currentBid} (Bid)",
    "component.artworkGrids.artworkGridItem.bidderPosition.defaultText:":
      "{currentBid} (Starting bid)",
    "component.artworkGrids.artworkGridItem.bidderPosition.bidSingular": "1 bid",
    "component.artworkGrids.artworkGridItem.bidderPosition.bidPlural": "{bidderPositions} bids",
    "component.artworkGrids.artworkGridItem.saleMessage": "Price on request",
    "component.artworkGrids.artworksFilterHeader.title": "Sort & Filter",
    "component.artworkGrids.filteredArtworkGridZeroState.zeroStateMessage":
      "No results found\nPlease try another search.",
    "component.artworkGrids.filteredArtworkGridZeroState.clearButton": "Clear filters",
    "component.artworkRail.artworkRailCard.lotText": "Lot {lotLabel}",
    "component.entityList.andText": " and ",
    "component.entityList.othersText": "others",
    "component.headerArtworksFilter.headerArtworksFilter.title": "Sort & Filter",
    "component.headerArtworksFilter.headerArtworksFilter.totalWorksShown": "Showing {total} works",
    "component.customShareSheet.share": "Share",
    "component.menuItem.beta": "Beta",
    "component.searchInput.cancel": "Cancel",
    "component.sectionTitle.rightButton.viewAll": "View All",
    "component.photos.doneText": "Done",
    "component.relatedArtists.relatedArtists.section.title": "Related artists",
    "component.relatedArtists.relatedArtist.workText": "work",
    "component.relatedArtists.relatedArtist.workTextPlural": "works",
    "component.relatedArtists.relatedArtist.forSaleText": "for sale",
    "component.show.showArtistsPreview.artists": "Artists",
    "component.show.showArtistsPreview.caretButton": "View all {length} artists",
    "component.show.showArtworksPreview.caretButton": "View all {length} works",
    "container.inbox.inquiries": "Inquiries",
    "container.inbox.bids": "Bids",
    "container.inquiry.sendButton.sending": "Sending...",
    "container.inquiry.sendButton.send": "Send",
    "container.inquiry.cancel": "Cancel",
    "container.worksForYou.zeroState.title": "You haven’t followed any artists yet",
    "container.worksForYou.zeroState.subtitle":
      "Follow artists to see new works that have been added to Artsy.",
    "scene.about.about": "About",
    "scene.about.termsOfUse": "Terms of Use",
    "scene.about.privacyPolicy": "Privacy Policy",
    "scene.about.conditionsOfSale": "Conditions of Sale",
    "scene.articles.articlesList.title": "Market News",
    "scene.artist.tabs.overview": "Overview",
    "scene.artist.tabs.artworks": "Artworks",
    "scene.artist.tabs.insights": "Insights",
    "scene.artist.tabs.noArtworks":
      "There aren’t any works available by the artist at this time. Follow to receive notifications when new works are added.",
    "scene.artist.popover.title": "Sorry, an error occured",
    "scene.artist.popover.message": "Failed to get saved search criteria",
    "scene.artistArticles.artistArticles.title": "{name} articles",
    "scene.artistSeries.artistSeries.moreSeries": "More series by this artist",
    "scene.artistSeries.artistSeries.totalWorksShown": "Showing {total} works",
    "scene.artistSeries.artistSeriesFullArtistSeries.header": "Artist Series",
    "scene.artistSeries.artistSeriesMeta.follow": "Follow",
    "scene.artistSeries.artistSeriesMeta.following": "Following",
    "scene.artistSeries.artistSeriesMoreSeries.viewAll": "View All {totalCount}",
    "scene.artistShows.artistShows2.pastShows": "Past Shows",
    "scene.artwork.components.commercialButtons.bidButton.registration.toBid": "Register to bid",
    "scene.artwork.components.commercialButtons.bidButton.registration.pending":
      "Registration pending",
    "scene.artwork.components.commercialButtons.bidButton.registration.complete":
      "Registration complete",
    "scene.artwork.components.commercialButtons.bidButton.registration.closed":
      "Registration closed",
    "scene.artwork.components.commercialButtons.bidButton.increaseMaxBid": "Increase max bid",
    "scene.artwork.components.commercialButtons.bidButton.bid": "Bid",
    "scene.artwork.components.commercialButtons.bidButton.watchLive": "Watch live bidding",
    "scene.artwork.components.commercialButtons.bidButton.enterLive": "Enter live bidding",
    "scene.artwork.components.commercialButtons.bidButton.identityVerificationRequiredMessage.message":
      "Identity verification required to bid.",
    "scene.artwork.components.commercialButtons.bidButton.identityVerificationRequiredMessage.faq":
      "FAQ",
    "scene.artwork.components.commercialButtons.buyNowButton.error.title":
      "Sorry, we couldn't process the request.",
    "scene.artwork.components.commercialButtons.buyNowButton.error.message":
      "Please try again or contact orders@artsy.net for help.",
    "scene.artwork.components.commercialButtons.buyNowButton.error.retry": "Retry",
    "scene.artwork.components.commercialButtons.buyNowButton.error.Cancel": "Cancel",
    "scene.artwork.components.commercialButtons.buyNowButton.buyNow": "Buy Now",
    "scene.artwork.components.commercialButtons.buyNowButton.purchase": "Purchase",
    "scene.artwork.components.commercialButtons.buyNowButton.purchaseWithSaleMessage":
      "purchase {saleMessage}",
    "scene.artwork.components.commercialButtons.collapsibleArtworkDetails.artworkDetailItems.price":
      "Price",
    "scene.artwork.components.commercialButtons.collapsibleArtworkDetails.artworkDetailItems.medium":
      "Medium",
    "scene.artwork.components.commercialButtons.collapsibleArtworkDetails.artworkDetailItems.manufacturer":
      "Manufacturer",
    "scene.artwork.components.commercialButtons.collapsibleArtworkDetails.artworkDetailItems.publisher":
      "Publisher",
    "scene.artwork.components.commercialButtons.collapsibleArtworkDetails.artworkDetailItems.materials":
      "Materials",
    "scene.artwork.components.commercialButtons.collapsibleArtworkDetails.artworkDetailItems.classification":
      "Classification",
    "scene.artwork.components.commercialButtons.collapsibleArtworkDetails.artworkDetailItems.dimensions":
      "Dimensions",
    "scene.artwork.components.commercialButtons.collapsibleArtworkDetails.artworkDetailItems.signature":
      "Signature",
    "scene.artwork.components.commercialButtons.collapsibleArtworkDetails.artworkDetailItems.frame":
      "Frame",
    "scene.artwork.components.commercialButtons.collapsibleArtworkDetails.artworkDetailItems.certificate":
      "Certificate of Authenticity",
    "scene.artwork.components.commercialButtons.collapsibleArtworkDetails.artworkDetailItems.condition":
      "Condition",
    "scene.artwork.components.aboutArtist.aboutTheArtist": "About the artist",
    "scene.artwork.components.aboutArtist.aboutTheArtists": "About the artists",
    "scene.artwork.components.aboutWork.aboutTheWork": "About the work",
    "scene.artwork.components.aboutWork.fromArtsySpecialist": "From Artsy Specialist:",
    "scene.artwork.components.artworkActions.computedTitleWithNames": "{title} by {names} on Artsy",
    "scene.artwork.components.artworkActions.computedTitle": "{title} on Artsy",
    "scene.artwork.components.artworkActions.watchLot": "Watch lot",
    "scene.artwork.components.artworkActions.save": "Save",
    "scene.artwork.components.artworkActions.saved": "Saved",
    "scene.artwork.components.artworkActions.viewInRoom": "View in Room",
    "scene.artwork.components.artworkActions.share": "Share",
    "scene.artwork.components.artworkDetails.listItems.medium": "Medium",
    "scene.artwork.components.artworkDetails.listItems.condition": "Condition",
    "scene.artwork.components.artworkDetails.listItems.signature": "Signature",
    "scene.artwork.components.artworkDetails.listItems.certificateOfAuthenticity":
      "Certificate of Authenticity",
    "scene.artwork.components.artworkDetails.listItems.frame": "Frame",
    "scene.artwork.components.artworkDetails.listItems.series": "Series",
    "scene.artwork.components.artworkDetails.listItems.publisher": "Publisher",
    "scene.artwork.components.artworkDetails.listItems.manufacturer": "Manufacturer",
    "scene.artwork.components.artworkDetails.listItems.imageRights": "Image rights",
    "scene.artwork.components.artworkDetails.artworkDetails": "Artwork details",
    "scene.artwork.components.artworkHistory.sections.provenance": "Provenance",
    "scene.artwork.components.artworkHistory.sections.exhibitionHistory": "Exhibition History",
    "scene.artwork.components.artworkHistory.sections.literature": "Bibliography",
    "scene.artwork.components.artworkSeriesRails.section.title": "More from this series",
    "scene.artwork.components.artworkTombstone.more": "more",
    "scene.artwork.components.artworkTombstone.lot": "Lot {lotLabel}",
    "scene.artwork.components.artworkTombstone.estimatedValue": "Estimated value: {estimate}",
    "scene.artwork.components.auctionPrice.bidsCountSingular": "1 bid",
    "scene.artwork.components.auctionPrice.bidsCountPlural": "{bidsCount} bids",
    "scene.artwork.components.auctionPrice.biddingClosed": "Bidding closed",
    "scene.artwork.components.auctionPrice.currentBid": "Current bid",
    "scene.artwork.components.auctionPrice.startingBid": "Starting bid",
    "scene.artwork.components.auctionPrice.yourMaxBid": "Your max: {myMaxBid}",
    "scene.artwork.components.auctionPrice.auctionHas": "This auction has a ",
    "scene.artwork.components.auctionPrice.buyersPremium": "buyer's premium",
    "scene.artwork.components.auctionPrice.shipping":
      "Shipping, taxes, and additional fees may apply.",
    "scene.artwork.components.commercialEditionSetInformation.editionSize": "Edition size",
    "scene.artwork.components.commercialInformation.saleMessage": "Price on request",
    "scene.artwork.components.commercialInformation.newSaleMessage.biddingClosed": "Bidding closed",
    "scene.artwork.components.commercialInformation.newSaleMessage.forSale": "For sale",
    "scene.artwork.components.CommercialPartnerInformation.taxes": "Taxes may apply at checkout. ",
    "scene.artwork.components.CommercialPartnerInformation.learnMore": "Learn more.",
    "scene.artwork.components.CommercialPartnerInformation.shipsFrom":
      "Ships from {shippingOrigin}",
    "scene.artwork.components.contextCard.header.inAuction": "In auction",
    "scene.artwork.components.contextCard.header.inFair": "In Fair",
    "scene.artwork.components.contextCard.header.inShow": "In Show",
    "scene.artwork.components.followArtistLink.followButtonText.following": "Following",
    "scene.artwork.components.followArtistLink.followButtonText.follow": "Follow",
    "scene.artwork.components.partnerCard.partnerTypeDisplayText.gallery": "gallery",
    "scene.artwork.components.partnerCard.partnerTypeDisplayText.institution": "institution",
    "scene.artwork.components.requestConditionReport.presentErrorModal.message":
      "There was a problem processing your request. Please try again.",
    "scene.artwork.components.requestConditionReport.requestReport": "Request condition report",
    "scene.artwork.components.requestConditionReport.modal.error.headerText": "An error occurred",
    "scene.artwork.components.requestConditionReport.modal.headerText":
      "Condition Report Requested",
    "scene.artwork.components.requestConditionReport.modal.detailText":
      "We have received your request.\nThe condition report will be sent to {email}.\nFor questions contact specialist@artsy.net.",
    "scene.home.newWorksForYou.title": "New Works for You",
    "scene.home.yourActiveBids.title": "Your Active Bids",
    "scene.home.auctionLotsForYouEndingSoon.title": "Auction Lots for You Ending Soon",
    "scene.home.auctions.title": "Auctions",
    "scene.home.auctions.subtitle": "Discover and bid on works for you",
    "scene.home.auctionResultsForArtistsYouFollow.title": "Auction Results for Artists You Follow",
    "scene.home.marketNews.title": "Market News",
    "scene.home.recommendedArtists.title": "Recommended Artists",
    "scene.home.showsForYou.title": "Shows for You",
    "scene.home.trove.title": "Trove",
    "scene.home.viewingRooms.title": "Viewing Rooms",
    "scene.home.collections.title": "Collections",
    "scene.home.collections.subtitle": "The newest works curated by Artsy",
    "scene.home.artworkRecommendations.title": "Artwork Recommendations",
    "scene.home.featuredFairs.title": "Featured Fairs",
    "scene.home.featuredFairs.subtitle": "See works in top art fairs",
    "scene.home.popularArtists.title": "Popular Artists",
    "scene.home.recentlyViewed.title": "Recently Viewed",
    "scene.home.similarToWorks.title": "Similar to Works You've Viewed",
    "scene.myCollection.myCollection.button.addWorks": "Add Works",
    "scene.myCollection.myCollectionArtwork.zeroState.title": "Your art collection in your pocket.",
    "scene.myCollection.myCollectionArtwork.zeroState.subtitle":
      "Keep track of your collection all in one place and get market insights",
    "scene.myCollection.myCollectionArtwork.zeroState.button": "Add Artwork",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.tabs.collection": "My Collection",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.tabs.savedWorks": "Saved Works",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.myProfileHeader.memberSince":
      "Member since {year}",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.myProfileHeader.settings": "Settings",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.myProfileHeader.editProfile":
      "Edit Profile",
    "scene.search.search.searchInputContainer.placeholder":
      "Search artists, artworks, galleries, etc",
    "scene.search.recentSearches.section.title": "Recent Searches",
    "scene.search.recentSearches.noRecentSearches": "We’ll save your recent searches here",
    "palette.elements.button.followButton.follow": "Follow",
    "palette.elements.button.followButton.following": "Following",
  },
  fr: {
    "component.artist.articles.section.title": "Articles en vedette",
    "component.artist.artistabout.artistseries.header": "Meilleure série d'artistes",
    "component.artist.artistaboutshows.featuring": "Spectacles mettant en vedette {artistName}",
    "component.artist.artistaboutshows.button": "Voir tous les spectacles passés",
    "component.artist.artistartworks.artistcollectionsrails.section.title": "Collections iconiques",
    "component.artist.artistartworks.artistnotableworksrails.section.title": "Œuvres remarquables",
    "component.artist.artistartworks.createsavedsearchmodal.popover.title":
      "Votre alerte a été créée.",
    "component.artist.artistartworks.createsavedsearchmodal.popover.message":
      "Modifiez vos alertes dans votre profil, dans Paramètres.",
    "component.artist.artistartworks.savedsearchbuttonv2.title": "Créer une alerte",
    "component.artist.artistinsights.artistinsights.section.title":
      "Filtrer les résultats des enchères",
    "component.artist.artistinsights.artistinsightsauctionresults.renderauctionresultsmodal.text1":
      "Ces résultats d'enchères rassemblent les données de vente des meilleures maisons d'enchères du monde entier, notamment Christie's, Sotheby's, Phillips et Bonhams. Les résultats sont mis à jour quotidiennement.",
    "component.artist.artistinsights.artistinsightsauctionresults.renderauctionresultsmodal.text2":
      "Veuillez noter que le prix de vente comprend le prix d'adjudication et la commission de l'acheteur, ainsi que tout autre frais supplémentaire (par exemple, le droit de suite de l'artiste).",
    "component.artist.artistinsights.artistinsightsauctionresults.infobutton.title":
      "Résultats des enchères",
    "component.artist.artistinsights.artistinsightsauctionresults.sortmode.sortdescription":
      "Trié par {sortDescription}",
    "component.artist.artistinsights.artistinsightsauctionresults.resultsText": "résultat",
    "component.artist.artistinsights.artistinsightsauctionresults.resultsTextPlural": "résultats",
    "component.artist.artistinsights.marketstats.renderinfomodal.text1":
      "Les points de données suivants donnent un aperçu du marché des enchères d'un artiste pour un objet spécifique (par exemple, photographie, peinture) au cours des 36 derniers mois.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text2":
      "Ces signaux de marché rassemblent les données des meilleures maisons de vente aux enchères du monde, notamment Christie's, Sotheby's, Phillips et Bonhams.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text3":
      "Dans cet ensemble de données, veuillez noter que le prix de vente comprend le prix d'adjudication et la prime de l'acheteur, ainsi que tout autre frais supplémentaire (par exemple, le droit de suite de l'artiste). L'ensemble de données ne comprend que les œuvres d'une valeur supérieure à 1 000 $.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text4":
      "Nombre moyen annuel de lots vendus",
    "component.artist.artistinsights.marketstats.renderinfomodal.text5":
      "Le nombre moyen de lots vendus par an aux enchères au cours des 36 derniers mois.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text6": "Taux de vente",
    "component.artist.artistinsights.marketstats.renderinfomodal.text7":
      "Le pourcentage de lots mis aux enchères qui se sont vendus au cours des 36 derniers mois.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text8": "Prix de vente moyen",
    "component.artist.artistinsights.marketstats.renderinfomodal.text9":
      "Le prix de vente moyen des lots vendus aux enchères au cours des 36 derniers mois.",
    "component.artist.artistinsights.marketstats.renderinfomodal.text10":
      "Prix de vente supérieur à l'estimation",
    "component.artist.artistinsights.marketstats.renderinfomodal.text11":
      "Différence moyenne en pourcentage du prix de vente par rapport à l'estimation médiane (le point médian des estimations basse et haute fixées par la maison de vente aux enchères avant la vente aux enchères) pour les lots vendus aux enchères au cours des 36 derniers mois.",
    "component.artist.artistinsights.marketstats.infobutton.title": "Signaux du marché",
    "component.artist.artistinsights.marketstats.averagetext": "Moyennes sur les 36 derniers mois",
    "component.artist.artistinsights.marketstats.select.title": "Sélectionnez le support",
    "component.artist.artistinsights.marketstats.annuallotssold": "Lots vendus à l'année",
    "component.artist.artistinsights.marketstats.sellthroughrate": "Taux de vente",
    "component.artist.artistinsights.marketstats.saleprice": "Prix de vente",
    "component.artist.artistinsights.marketstats.salepriceoverestimate":
      "Prix de vente supérieur à l'estimation",
    "component.artist.artistConsignButton.headline.default":
      "Vendez des œuvres d'art de votre collection",
    "component.artist.artistConsignButton.headline.inMicrofunnel": "Vendez votre {name}",
    "component.artist.artistConsignButton.consignText": "Consignez avec Artsy",
    "component.artist.artistHeader.workText": "oeuvre",
    "component.artist.artistHeader.workTextPlural": "oeuvres",
    "component.artist.artistHeader.followerText": "admirateur",
    "component.artist.artistHeader.followerTextPlural": "admirateurs",
    "component.artist.biography.section.title": "Biographie",
    "component.artworkGrids.artworkGridItem.lotText": "Lot {lotLabel}",
    "component.artworkGrids.artworkGridItem.soldForText": "Vendu pour {realizedPrize}",
    "component.artworkGrids.artworkGridItem.biddingClosedText": "Enchères fermées",
    "component.artworkGrids.artworkGridItem.bidderPosition.smallTileText":
      "{currentBid} (Offre d'achat)",
    "component.artworkGrids.artworkGridItem.bidderPosition.defaultText:":
      "{currentBid} (Enchère de départ",
    "component.artworkGrids.artworkGridItem.bidderPosition.bidSingular": "Une offre",
    "component.artworkGrids.artworkGridItem.bidderPosition.bidPlural": "{bidderPositions} enchères",
    "component.artworkGrids.artworkGridItem.saleMessage": "Prix sur demande",
    "component.artworkGrids.artworksFilterHeader.title": "Trier et filtrer",
    "component.artworkGrids.filteredArtworkGridZeroState.zeroStateMessage":
      "Aucun résultat trouvé\nVeuillez essayer une autre recherche.",
    "component.artworkGrids.filteredArtworkGridZeroState.clearButton": "Effacer les filtres",
    "component.artworkRail.artworkRailCard.lotText": "Lot {lotLabel}",
    "component.entityList.andText": " et ",
    "component.entityList.othersText": "de plus",
    "component.headerArtworksFilter.headerArtworksFilter.title": "Trier et filtrer",
    "component.headerArtworksFilter.headerArtworksFilter.totalWorksShown":
      "Affichage de {total} œuvres d'art",
    "component.customShareSheet.share": "Partager",
    "component.menuItem.beta": "Bêta",
    "component.searchInput.cancel": "Annuler",
    "component.sectionTitle.rightButton.viewAll": "Voir tout",
    "component.photos.doneText": "Finir",
    "component.relatedArtists.relatedArtists.section.title": "Artistes associés",
    "component.relatedArtists.relatedArtist.workText": "oeuvre",
    "component.relatedArtists.relatedArtist.workTextPlural": "oeuvres",
    "component.relatedArtists.relatedArtist.forSaleText": "à vendre",
    "component.show.showArtistsPreview.artists": "Artistes",
    "component.show.showArtistsPreview.caretButton": "Voir tous les {length} artistes",
    "component.show.showArtworksPreview.caretButton": "Voir les {length} œuvres",
    "container.inbox.inquiries": "Demandes",
    "container.inbox.bids": "Enchères",
    "container.inquiry.sendButton.sending": "Envoi en cours...",
    "container.inquiry.sendButton.send": "Envoyer",
    "container.inquiry.cancel": "Annuler",
    "container.worksForYou.zeroState.title": "Vous n'avez encore suivi aucun artiste",
    "container.worksForYou.zeroState.subtitle":
      "Suivez les artistes pour voir les nouvelles œuvres qui ont été ajoutées à Artsy.",
    "scene.about.about": "au sujet de",
    "scene.about.termsOfUse": "Conditions d'utilisation",
    "scene.about.privacyPolicy": "Politique de confidentialité",
    "scene.about.conditionsOfSale": "Conditions de vente",
    "scene.articles.articlesList.title": "Articles de {name}",
    "scene.artist.tabs.overview": "Aperçu",
    "scene.artist.tabs.artworks": "Oeuvres d'art",
    "scene.artist.tabs.insights": "Connaissances",
    "scene.artist.tabs.noArtworks":
      "Aucune œuvre de l'artiste n'est disponible pour le moment. Suivez pour recevoir des notifications lorsque de nouvelles œuvres sont ajoutées.",
    "scene.artist.popover.title": "Désolé, une erreur s'est produite",
    "scene.artist.popover.message": "Impossible d'obtenir les critères de recherche enregistrés",
    "scene.artistSeries.artistSeries.moreSeries": "Plus de séries de cet artiste",
    "scene.artistSeries.artistSeries.totalWorksShown": "Affichage de {total} œuvres d'art",
    "scene.artistSeries.artistSeriesFullArtistSeries.header": "Artiste Série",
    "scene.artistSeries.artistSeriesMeta.follow": "Suivre",
    "scene.artistSeries.artistSeriesMeta.following": "Suivant",
    "scene.artistSeries.artistSeriesMoreSeries.viewAll": "Voir les {totalCount}",
    "scene.artistShows.artistShows2.pastShows": "Spectacles passés",
    "scene.artwork.components.aboutArtist.aboutTheArtist": "À propos de l'artiste",
    "scene.artwork.components.aboutArtist.aboutTheArtists": "A propos des artistes",
    "scene.artwork.components.aboutWork.aboutTheWork": "À propos de l'oeuvre",
    "scene.artwork.components.aboutWork.fromArtsySpecialist": "Du spécialiste Artsy:",
    "scene.artwork.components.artworkActions.computedTitleWithNames":
      "{title} par {names} sur Artsy",
    "scene.artwork.components.artworkActions.computedTitle": "{title} sur Artsy",
    "scene.artwork.components.artworkActions.watchLot": "Regardez lot",
    "scene.artwork.components.artworkActions.save": "Enregistrer",
    "scene.artwork.components.artworkActions.saved": "Enregistré",
    "scene.artwork.components.artworkActions.viewInRoom": "Voir dans la chambre",
    "scene.artwork.components.artworkActions.share": "Partager",
    "scene.artwork.components.artworkDetails.listItems.medium": "Moyen",
    "scene.artwork.components.artworkDetails.listItems.condition": "État",
    "scene.artwork.components.artworkDetails.listItems.signature": "Signature",
    "scene.artwork.components.artworkDetails.listItems.certificateOfAuthenticity":
      "Certificat d'authenticité",
    "scene.artwork.components.artworkDetails.listItems.frame": "Cadre",
    "scene.artwork.components.artworkDetails.listItems.series": "Séries",
    "scene.artwork.components.artworkDetails.listItems.publisher": "Éditeur",
    "scene.artwork.components.artworkDetails.listItems.manufacturer": "Fabricant",
    "scene.artwork.components.artworkDetails.listItems.imageRights": "Droits d'image",
    "scene.artwork.components.artworkDetails.artworkDetails": "Détails de l'œuvre",
    "scene.artwork.components.artworkHistory.sections.provenance": "Provenance",
    "scene.artwork.components.artworkHistory.sections.exhibitionHistory":
      "Historique de l'exposition",
    "scene.artwork.components.artworkHistory.sections.literature": "Bibliographie",
    "scene.artwork.components.artworkSeriesRails.section.title": "Plus de cette série",
    "scene.artwork.components.artworkTombstone.more": "plus",
    "scene.artwork.components.artworkTombstone.lot": "Lot {lotLabel}",
    "scene.artwork.components.artworkTombstone.estimatedValue": "Valeur estimée: {estimate}",
    "scene.artwork.components.auctionPrice.bidsCountSingular": "Une offre",
    "scene.artwork.components.auctionPrice.bidsCountPlural": "{bidsCount} enchères",
    "scene.artwork.components.auctionPrice.biddingClosed": "Enchères fermées",
    "scene.artwork.components.auctionPrice.currentBid": "Enchère actuelle",
    "scene.artwork.components.auctionPrice.startingBid": "Enchère de départ",
    "scene.artwork.components.auctionPrice.yourMaxBid": "Votre maximum: {myMaxBid}",
    "scene.artwork.components.auctionPrice.auctionHas": "Cette enchère a un ",
    "scene.artwork.components.auctionPrice.buyersPremium": "prime de l'acheteur",
    "scene.artwork.components.auctionPrice.shipping":
      "Des frais d'expédition, des taxes et des frais supplémentaires peuvent s'appliquer.",
    "scene.artwork.components.commercialEditionSetInformation.editionSize": "Taille de l'édition",
    "scene.artwork.components.commercialInformation.saleMessage": "Prix sur demande",
    "scene.artwork.components.commercialInformation.newSaleMessage.biddingClosed":
      "Enchères fermées",
    "scene.artwork.components.commercialInformation.newSaleMessage.forSale": "À vendre",
    "scene.artwork.components.CommercialPartnerInformation.taxes":
      "Des taxes peuvent s'appliquer au moment du paiement. ",
    "scene.artwork.components.CommercialPartnerInformation.learnMore": "Apprendre encore plus.",
    "scene.artwork.components.CommercialPartnerInformation.shipsFrom":
      "Expédié depuis {shippingOrigin}",
    "scene.artwork.components.contextCard.header.inAuction": "Aux enchères",
    "scene.artwork.components.contextCard.header.inFair": "En Fair",
    "scene.artwork.components.contextCard.header.inShow": "En spectacle",
    "scene.artwork.components.followArtistLink.followButtonText.following": "Suivant",
    "scene.artwork.components.followArtistLink.followButtonText.follow": "Suivre",
    "scene.artwork.components.partnerCard.partnerTypeDisplayText.gallery": "Galerie",
    "scene.artwork.components.partnerCard.partnerTypeDisplayText.institution": "institution",
    "scene.artwork.components.requestConditionReport.presentErrorModal.message":
      "Il y avait un problème lors du traitement de votre demande. Veuillez réessayer.",
    "scene.artwork.components.requestConditionReport.requestReport": "Demander un rapport d'état",
    "scene.artwork.components.requestConditionReport.modal.error.headerText":
      "Une erreur s'est produite",
    "scene.artwork.components.requestConditionReport.modal.headerText": "Rapport d'état demandé",
    "scene.artwork.components.requestConditionReport.modal.detailText":
      "Nous avons reçu votre demande.\nLe rapport d'état sera envoyé à {email}.\nPour toute question, contactez specialist@artsy.net.",
    "scene.home.newWorksForYou.title": "De nouvelles oeuvres pour vous",
    "scene.home.yourActiveBids.title": "Vos enchères actives",
    "scene.home.auctionLotsForYouEndingSoon.title":
      "Lots d'enchères pour vous se terminant bientôt",
    "scene.home.auctions.title": "Les enchères",
    "scene.home.auctions.subtitle": "Découvrez et enchérissez sur des œuvres pour vous",
    "scene.home.auctionResultsForArtistsYouFollow.title":
      "Résultats des enchères pour les artistes que vous suivez",
    "scene.home.marketNews.title": "Nouvelles du marché",
    "scene.home.recommendedArtists.title": "Artistes recommandés",
    "scene.home.showsForYou.title": "Spectacles pour Vous",
    "scene.home.trove.title": "Trove",
    "scene.home.viewingRooms.title": "Salles de visualisation",
    "scene.home.collections.title": "Collections",
    "scene.home.collections.subtitle": "Les dernières œuvres organisées par Artsy",
    "scene.home.artworkRecommendations.title": "Recommandations d'illustrations",
    "scene.home.featuredFairs.title": "Stands en vedette",
    "scene.home.featuredFairs.subtitle": "Voir les œuvres dans les meilleures foires d'art",
    "scene.home.popularArtists.title": "Artistes populaires",
    "scene.home.recentlyViewed.title": "vu récemment",
    "scene.home.similarToWorks.title": "Similaire aux œuvres que vous avez vues",
    "scene.myCollection.myCollection.button.addWorks": "Ajouter des oeuvres",
    "scene.myCollection.myCollectionArtwork.zeroState.title":
      "Votre collection d'art dans votre poche.",
    "scene.myCollection.myCollectionArtwork.zeroState.subtitle":
      "Gardez une trace de votre collection en un seul endroit et obtenez des informations sur le marché",
    "scene.myCollection.myCollectionArtwork.zeroState.button": "Ajouter des oeuvres",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.tabs.collection": "Ma Collection",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.tabs.savedWorks":
      "Oeuvres enregistrées",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.myProfileHeader.memberSince":
      "Membre depuis {year}",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.myProfileHeader.settings": "Réglages",
    "scene.myProfile.myProfileHeaderMyCollectionAndSavedWorks.myProfileHeader.editProfile":
      "Editer le profil",
    "scene.search.search.searchInputContainer.placeholder":
      "Rechercher des artistes, des œuvres d'art, des galeries, etc.",
    "scene.search.recentSearches.section.title": "Recherches Récentes",
    "scene.search.recentSearches.noRecentSearches":
      "Nous enregistrerons vos recherches récentes ici",
    "palette.elements.button.followButton.follow": "Suivre",
    "palette.elements.button.followButton.following": "Suivant",
  },
}
