#!/usr/bin/env bash
set -euxo pipefail

source ./scripts/ci/ci-setup-export-vars

./scripts/deploys/check_version_synced
./scripts/deploys/check_build_status_gh android

git push origin "$LOCAL_BRANCH:beta-android" -f --no-verify
