#!/usr/bin/env bash
set -euxo pipefail

./scripts/setup/download-assets-ios

DISTRIBUTION_TARGET="${1-"TESTFLIGHT"}"
if [ $DISTRIBUTION_TARGET == "FIREBASE" ]; then
  bundle exec fastlane ship_beta_ios deployment_target:firebase
elif [ $DISTRIBUTION_TARGET == "TESTFLIGHT" ]; then
  bundle exec fastlane ship_beta_ios deployment_target:testflight
fi
