#!/usr/bin/env bash
set -exo pipefail

./scripts/setup/download-assets-android

DISTRIBUTION_TARGET="${1-"PLAY_STORE"}"
if [ $DISTRIBUTION_TARGET == "FIREBASE" ]; then
  bundle exec fastlane ship_beta_android deployment_target:firebase
elif [ $DISTRIBUTION_TARGET == "PLAY_STORE" ]; then
  bundle exec fastlane ship_beta_android deployment_target:play_store
fi
