export const ShowFixture = {
  id: "anderson-fine-art-gallery-flickinger-collection",
  _id: "5b368a02275b245afc034d6f",
  openingReceptionText: "",
  city: "Sea Island ",
  is_local_discovery: false,
  isStubShow: false,
  is_followed: false,
  status: "closed",
  end_at: "2018-10-30T12:00:00+00:00",
  start_at: "2018-07-01T12:00:00+00:00",
  pressReleaseUrl: "https://example.com",
  location: {
    gravityID: "TG9jYXRpb246NWIzNjQ2NjRjYjRjMjcxNzQzNDkwMTkx",
    id: "5b364664cb4c271743490191",
    city: "Sea Island ",
    address: "Online Exclusive",
    address_2: "",
    coordinates: null,
    day_schedules: [],
    summary: "",
    openingHours: {
      __typename: "OpeningHoursText",
      text: "",
    },
    postal_code: "",
  },
  nearbyShows: {
    pageInfo: {
      startCursor: null,
      endCursor: null,
    },
    edges: [],
  },
  partner: {
    __typename: "Partner",
    name: "Two Palms",
    id: "UGFydG5lcjp0d28tcGFsbXM=",
    website: "",
    type: "Partner",
    href: "shows/two-palms",
  },
  artists_without_artworks: [
    {
      id: "QXJ0aXN0OnNhbS1mcmFuY2lz",
      _id: "4d8b92854eb68a1b2c0001b8",
      gravityID: "sam-francis",
      name: "Sam Francis",
      is_followed: false,
      href: "/artist/sam-francis",
      nationality: "American",
      birthday: "1923",
      deathday: "1994",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/wZ9dabmVZjtcaB_q_bKKzw/tall.jpg",
        id: "sam-francis",
      },
    },
  ],
  followedArtists: {
    edges: [
      {
        node: {
          artist: {
            id: "QXJ0aXN0OmhhbnMtaG9mbWFubg==",
            _id: "4d8b92614eb68a1b2c000064",
            gravityID: "hans-hofmann",
            name: "Hans Hofmann",
            is_followed: false,
            href: "/artist/hans-hofmann",
            nationality: "German-American",
            birthday: "1880",
            deathday: "1966",
            image: {
              url: "https://d32dm0rphc51dk.cloudfront.net/vRQdNHjLuWKadBXy9Fl4Pg/tall.jpg",
              id: "hans-hofmann",
            },
          },
        },
      },
      {
        node: {
          artist: {
            id: "QXJ0aXN0OnNhbS1mcmFuY2lz",
            _id: "4d8b92854eb68a1b2c0001b8",
            gravityID: "sam-francis",
            name: "Sam Francis",
            is_followed: false,
            href: "/artist/sam-francis",
            nationality: "American",
            birthday: "1923",
            deathday: "1994",
            image: {
              url: "https://d32dm0rphc51dk.cloudfront.net/wZ9dabmVZjtcaB_q_bKKzw/tall.jpg",
              id: "sam-francis",
            },
          },
        },
      },
      {
        node: {
          artist: {
            id: "QXJ0aXN0OnBhYmxvLXBpY2Fzc28=",
            _id: "4d8b928b4eb68a1b2c0001f2",
            gravityID: "pablo-picasso",
            name: "Pablo Picasso",
            is_followed: false,
            href: "/artist/pablo-picasso",
            nationality: "Spanish",
            birthday: "1881",
            deathday: "1973",
            image: {
              url: "https://d32dm0rphc51dk.cloudfront.net/i3rCA3IaKE-cLBnc-U5swQ/tall.jpg",
              id: "pablo-picasso",
            },
          },
        },
      },
    ],
  },
  artists: [
    {
      id: "QXJ0aXN0OmhhbnMtaG9mbWFubg==",
      _id: "4d8b92614eb68a1b2c000064",
      gravityID: "hans-hofmann",
      name: "Hans Hofmann",
      is_followed: false,
      href: "/artist/hans-hofmann",
      nationality: "German-American",
      birthday: "1880",
      deathday: "1966",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/vRQdNHjLuWKadBXy9Fl4Pg/tall.jpg",
        id: "hans-hofmann",
      },
    },
    {
      id: "QXJ0aXN0OmRhdmlkLWhvY2tuZXk=",
      _id: "4d8b92854eb68a1b2c0001b6",
      gravityID: "david-hockney",
      name: "David Hockney",
      is_followed: false,
      href: "/artist/david-hockney",
      nationality: "British",
      birthday: "1937",
      deathday: "",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/kCJVZo7bcqVrjnQ22QHhvg/tall.jpg",
        id: "david-hockney",
      },
    },
    {
      id: "QXJ0aXN0OnNhbS1mcmFuY2lz",
      _id: "4d8b92854eb68a1b2c0001b8",
      gravityID: "sam-francis",
      name: "Sam Francis",
      is_followed: false,
      href: "/artist/sam-francis",
      nationality: "American",
      birthday: "1923",
      deathday: "1994",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/wZ9dabmVZjtcaB_q_bKKzw/tall.jpg",
        id: "sam-francis",
      },
    },
    {
      id: "QXJ0aXN0OnBhYmxvLXBpY2Fzc28=",
      _id: "4d8b928b4eb68a1b2c0001f2",
      gravityID: "pablo-picasso",
      name: "Pablo Picasso",
      is_followed: false,
      href: "/artist/pablo-picasso",
      nationality: "Spanish",
      birthday: "1881",
      deathday: "1973",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/i3rCA3IaKE-cLBnc-U5swQ/tall.jpg",
        id: "pablo-picasso",
      },
    },
    {
      id: "QXJ0aXN0OndvbGYta2Fobg==",
      _id: "4d8b928b4eb68a1b2c0001fa",
      gravityID: "wolf-kahn",
      name: "Wolf Kahn",
      is_followed: false,
      href: "/artist/wolf-kahn",
      nationality: "American",
      birthday: "1927",
      deathday: "",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/pzYQSjFUn7MyELRIVyADjQ/tall.jpg",
        id: "wolf-kahn",
      },
    },
    {
      id: "QXJ0aXN0OnJvYmVydC1tb3RoZXJ3ZWxs",
      _id: "4d8b92a24eb68a1b2c000318",
      gravityID: "robert-motherwell",
      name: "Robert Motherwell",
      is_followed: false,
      href: "/artist/robert-motherwell",
      nationality: "American",
      birthday: "1915",
      deathday: "1991",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/BbPC9SljRn-_6AfewiQpxw/tall.jpg",
        id: "robert-motherwell",
      },
    },
    {
      id: "QXJ0aXN0OmppbS1kaW5l",
      _id: "4d8d1266876c697ae1000050",
      gravityID: "jim-dine",
      name: "Jim Dine",
      is_followed: false,
      href: "/artist/jim-dine",
      nationality: "American",
      birthday: "1935",
      deathday: "",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/Ll4gMf_OsLMehbgv05H6mw/tall.jpg",
        id: "jim-dine",
      },
    },
    {
      id: "QXJ0aXN0OmVsbHN3b3J0aC1rZWxseQ==",
      _id: "4dbe1873a671b202fd0001b3",
      gravityID: "ellsworth-kelly",
      name: "Ellsworth Kelly",
      is_followed: false,
      href: "/artist/ellsworth-kelly",
      nationality: "American",
      birthday: "1923",
      deathday: "2015",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/Bv9Hh3cYTCvc76NnZS4w4g/tall.jpg",
        id: "ellsworth-kelly",
      },
    },
    {
      id: "QXJ0aXN0OmJyaWRnZXQtcmlsZXk=",
      _id: "4ddbb26110c9af00010018a7",
      gravityID: "bridget-riley",
      name: "Bridget Riley",
      is_followed: false,
      href: "/artist/bridget-riley",
      nationality: "British",
      birthday: "1931",
      deathday: "",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/zLIFDjlzCw8ijOH9PPeasA/tall.jpg",
        id: "bridget-riley",
      },
    },
    {
      id: "QXJ0aXN0OnJpY2hhcmQtZGllYmVua29ybg==",
      _id: "4df4438f81d91d0001002d9c",
      gravityID: "richard-diebenkorn",
      name: "Richard Diebenkorn",
      is_followed: false,
      href: "/artist/richard-diebenkorn",
      nationality: "American",
      birthday: "1922",
      deathday: "1993",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/C5GfncAzGMsMf6A6RSfJEQ/tall.jpg",
        id: "richard-diebenkorn",
      },
    },
    {
      id: "QXJ0aXN0OmthcmVsLWFwcGVs",
      _id: "4df612a628eaa10001004397",
      gravityID: "karel-appel",
      name: "Karel Appel",
      is_followed: false,
      href: "/artist/karel-appel",
      nationality: "Dutch",
      birthday: "1921",
      deathday: "2006",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/puxzysW1yY3FCRLFaLFEQQ/tall.jpg",
        id: "karel-appel",
      },
    },
    {
      id: "QXJ0aXN0OmRhbGUtY2hpaHVseQ==",
      _id: "4e97356d4e77d300010008fa",
      gravityID: "dale-chihuly",
      name: "Dale Chihuly",
      is_followed: false,
      href: "/artist/dale-chihuly",
      nationality: "American",
      birthday: "1941",
      deathday: "",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/qfT1qZw8EGJguSakyhFxig/tall.jpg",
        id: "dale-chihuly",
      },
    },
    {
      id: "QXJ0aXN0OnBvbGx5LWFwZmVsYmF1bQ==",
      _id: "4f5f64c13b555230ac00003a",
      gravityID: "polly-apfelbaum",
      name: "Polly Apfelbaum",
      is_followed: false,
      href: "/artist/polly-apfelbaum",
      nationality: "American",
      birthday: "1955",
      deathday: "",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/MByqc96STE-fJtW4mZpgSg/tall.jpg",
        id: "polly-apfelbaum",
      },
    },
    {
      id: "QXJ0aXN0OmNhcm9seW4tYnJhZHk=",
      _id: "506b3335446617000200054c",
      gravityID: "carolyn-brady",
      name: "Carolyn Brady",
      is_followed: false,
      href: "/artist/carolyn-brady",
      nationality: "American",
      birthday: "1937",
      deathday: "2005",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/DH5Jtvy_a5d4Bb5hxB-Fxw/tall.jpg",
        id: "carolyn-brady",
      },
    },
    {
      id: "QXJ0aXN0Om5lbGwtYmxhaW5l",
      _id: "50c84c1e623327ed6c000c24",
      gravityID: "nell-blaine",
      name: "Nell Blaine",
      is_followed: false,
      href: "/artist/nell-blaine",
      nationality: "American",
      birthday: "1922",
      deathday: "1996",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/jr4zSDi7sXllVBNVhQardw/tall.jpg",
        id: "nell-blaine",
      },
    },
    {
      id: "QXJ0aXN0OmJydWNlLWJlYXNsZXk=",
      _id: "55fc7e16726169225600007c",
      gravityID: "bruce-beasley",
      name: "Bruce Beasley",
      is_followed: false,
      href: "/artist/bruce-beasley",
      nationality: "American",
      birthday: "1939",
      deathday: "",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/XazCw3_7ZEQz-sdkLDWXjA/tall.jpg",
        id: "bruce-beasley",
      },
    },
    {
      id: "QXJ0aXN0OnJvYmVydC1oYXJtcw==",
      _id: "568453ce66fd1c650b000057",
      gravityID: "robert-harms",
      name: "Robert Harms",
      is_followed: false,
      href: "/artist/robert-harms",
      nationality: "",
      birthday: "1962",
      deathday: "",
      image: {
        url: "https://d32dm0rphc51dk.cloudfront.net/i5_X3qJO8gFiyHrlHvAb-w/tall.jpg",
        id: "robert-harms",
      },
    },
  ],
  artworks: [
    {
      gravityID: "QXJ0d29yazpjYXJvbHluLWJyYWR5LXN0b3VyaGVhZC1hY3Jvc3MtdGhlLWxha2U=",
      id: "carolyn-brady-stourhead-across-the-lake",
      title: "Stourhead Across the Lake",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "carolyn-brady",
          name: "Carolyn Brady",
        },
      ],
      artist_names: "Carolyn Brady",
      image: {
        aspect_ratio: 1.53,
        id: "5b4b636f64067502ce65a990",
        url: "https://d32dm0rphc51dk.cloudfront.net/tH19ZfyCDocnNsKzXOZfHg/medium.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/tH19ZfyCDocnNsKzXOZfHg/medium.jpg",
          aspect_ratio: 1.53,
          id: "5b4b636f64067502ce65a990",
        },
      ],
      href: "/artwork/carolyn-brady-stourhead-across-the-lake",
      sale: null,
      is_in_auction: false,
      sale_message: "$15,000",
      price: "$15,000",
      availability: "for sale",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1997",
    },
    {
      gravityID: "QXJ0d29yazpyb2JlcnQtaGFybXMtYmx1ZmYtcm9hZA==",
      id: "robert-harms-bluff-road",
      title: "Bluff Road",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "robert-harms",
          name: "Robert Harms",
        },
      ],
      artist_names: "Robert Harms",
      image: {
        aspect_ratio: 1,
        id: "5b33ebad275b240e5f927a93",
        url: "https://d32dm0rphc51dk.cloudfront.net/xU1Y9RXzBJ0TY6G0ZvbHHw/larger.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/xU1Y9RXzBJ0TY6G0ZvbHHw/larger.jpg",
          aspect_ratio: 1,
          id: "5b33ebad275b240e5f927a93",
        },
      ],
      href: "/artwork/robert-harms-bluff-road",
      sale: null,
      is_in_auction: false,
      sale_message: "Sold",
      price: "$18,000",
      availability: "sold",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1998",
    },
    {
      gravityID: "QXJ0d29yazpqaW0tZGluZS1hbi1pbmZvcm1hbC10aWU=",
      id: "jim-dine-an-informal-tie",
      title: "An Informal Tie",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "jim-dine",
          name: "Jim Dine",
        },
      ],
      artist_names: "Jim Dine",
      image: {
        aspect_ratio: 0.51,
        id: "5b33e310cb4c273c8abed039",
        url: "https://d32dm0rphc51dk.cloudfront.net/dBBr15AyJ13x5heIyctJIA/tall.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/dBBr15AyJ13x5heIyctJIA/tall.jpg",
          aspect_ratio: 0.51,
          id: "5b33e310cb4c273c8abed039",
        },
      ],
      href: "/artwork/jim-dine-an-informal-tie",
      sale: null,
      is_in_auction: false,
      sale_message: "$14,000",
      price: "$14,000",
      availability: "for sale",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1961",
    },
    {
      gravityID: "QXJ0d29yazpyaWNoYXJkLWRpZWJlbmtvcm4tYmx1ZS13aXRoLXJlZC0xNQ==",
      id: "richard-diebenkorn-blue-with-red-15",
      title: "Blue with Red",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "richard-diebenkorn",
          name: "Richard Diebenkorn",
        },
      ],
      artist_names: "Richard Diebenkorn",
      image: {
        aspect_ratio: 0.71,
        id: "5b33d87dcd530e5746e1187b",
        url: "https://d32dm0rphc51dk.cloudfront.net/txGh8F3S_CDBKt6QPtjIBw/larger.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/txGh8F3S_CDBKt6QPtjIBw/larger.jpg",
          aspect_ratio: 0.71,
          id: "5b33d87dcd530e5746e1187b",
        },
      ],
      href: "/artwork/richard-diebenkorn-blue-with-red-15",
      sale: null,
      is_in_auction: false,
      sale_message: "Sold",
      price: "$35,000",
      availability: "sold",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1987",
    },
    {
      gravityID: "QXJ0d29yazprYXJlbC1hcHBlbC1oYXBweS1naG9zdA==",
      id: "karel-appel-happy-ghost",
      title: "Happy Ghost",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "karel-appel",
          name: "Karel Appel",
        },
      ],
      artist_names: "Karel Appel",
      image: {
        aspect_ratio: 0.78,
        id: "5b33c803a09a6779c76cd6af",
        url: "https://d32dm0rphc51dk.cloudfront.net/SUPKae4rRR1ZWs5mc70QJg/larger.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/SUPKae4rRR1ZWs5mc70QJg/larger.jpg",
          aspect_ratio: 0.78,
          id: "5b33c803a09a6779c76cd6af",
        },
      ],
      href: "/artwork/karel-appel-happy-ghost",
      sale: null,
      is_in_auction: false,
      sale_message: "$6,000",
      price: "$6,000",
      availability: "for sale",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1960",
    },
    {
      gravityID: "QXJ0d29yazpuZWxsLWJsYWluZS1hdWd1c3QtbGlnaHQ=",
      id: "nell-blaine-august-light",
      title: "August Light",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "nell-blaine",
          name: "Nell Blaine",
        },
      ],
      artist_names: "Nell Blaine",
      image: {
        aspect_ratio: 1.46,
        id: "5b33cf9b7076d070a64d7ac7",
        url: "https://d32dm0rphc51dk.cloudfront.net/P_4Avd1FcPjMKJ_aJFA1WQ/medium.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/P_4Avd1FcPjMKJ_aJFA1WQ/medium.jpg",
          aspect_ratio: 1.46,
          id: "5b33cf9b7076d070a64d7ac7",
        },
      ],
      href: "/artwork/nell-blaine-august-light",
      sale: null,
      is_in_auction: false,
      sale_message: "$10,000",
      price: "$10,000",
      availability: "for sale",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1989",
    },
    {
      gravityID: "QXJ0d29yazpicnVjZS1iZWFzbGV5LXZveWFnZXI=",
      id: "bruce-beasley-voyager",
      title: "Voyager",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "bruce-beasley",
          name: "Bruce Beasley",
        },
      ],
      artist_names: "Bruce Beasley",
      image: {
        aspect_ratio: 0.71,
        id: "5babb3f7c786fb5e3fc9f10f",
        url: "https://d32dm0rphc51dk.cloudfront.net/m7N4jeFJJr3FdFqU_0YDRg/medium.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/m7N4jeFJJr3FdFqU_0YDRg/medium.jpg",
          aspect_ratio: 0.71,
          id: "5babb3f7c786fb5e3fc9f10f",
        },
      ],
      href: "/artwork/bruce-beasley-voyager",
      sale: null,
      is_in_auction: false,
      sale_message: "Sold",
      price: "$30,000",
      availability: "sold",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1999",
    },
    {
      gravityID: "QXJ0d29yazpzYW0tZnJhbmNpcy11bmRlci1ibHVlLTM=",
      id: "sam-francis-under-blue-3",
      title: "Under Blue",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "sam-francis",
          name: "Sam Francis",
        },
      ],
      artist_names: "Sam Francis",
      image: {
        aspect_ratio: 1.35,
        id: "5b33ea9e5b2fba17ddc57257",
        url: "https://d32dm0rphc51dk.cloudfront.net/gz2wa9iBcZKB0ut6gMED1w/larger.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/gz2wa9iBcZKB0ut6gMED1w/larger.jpg",
          aspect_ratio: 1.35,
          id: "5b33ea9e5b2fba17ddc57257",
        },
      ],
      href: "/artwork/sam-francis-under-blue-3",
      sale: null,
      is_in_auction: false,
      sale_message: "$12,000",
      price: "$12,000",
      availability: "for sale",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1974",
    },
    {
      gravityID: "QXJ0d29yazpjYXJvbHluLWJyYWR5LXRhbWFyaW5k",
      id: "carolyn-brady-tamarind",
      title: "Tamarind",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "carolyn-brady",
          name: "Carolyn Brady",
        },
      ],
      artist_names: "Carolyn Brady",
      image: {
        aspect_ratio: 1.33,
        id: "5b33d4caa6ca6d137cebf02b",
        url: "https://d32dm0rphc51dk.cloudfront.net/tkm-BtRS1igRoRUx5SdOOA/larger.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/tkm-BtRS1igRoRUx5SdOOA/larger.jpg",
          aspect_ratio: 1.33,
          id: "5b33d4caa6ca6d137cebf02b",
        },
      ],
      href: "/artwork/carolyn-brady-tamarind",
      sale: null,
      is_in_auction: false,
      sale_message: "$4,500",
      price: "$4,500",
      availability: "for sale",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1999",
    },
    {
      gravityID: "QXJ0d29yazpyb2JlcnQtbW90aGVyd2VsbC1udW1iZXItOA==",
      id: "robert-motherwell-number-8",
      title: "Number 8",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "robert-motherwell",
          name: "Robert Motherwell",
        },
      ],
      artist_names: "Robert Motherwell",
      image: {
        aspect_ratio: 0.72,
        id: "5b4b8703a7bb3b324e71bb0b",
        url: "https://d32dm0rphc51dk.cloudfront.net/u-Onw4lFPIgSERW9vkizjA/larger.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/u-Onw4lFPIgSERW9vkizjA/larger.jpg",
          aspect_ratio: 0.72,
          id: "5b4b8703a7bb3b324e71bb0b",
        },
      ],
      href: "/artwork/robert-motherwell-number-8",
      sale: null,
      is_in_auction: false,
      sale_message: "$6,000",
      price: "$6,000",
      availability: "for sale",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "2000",
    },
    {
      gravityID: "QXJ0d29yazplbGxzd29ydGgta2VsbHktZ3JlZW4tY3VydmUtMTQ=",
      id: "ellsworth-kelly-green-curve-14",
      title: "Green Curve",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "ellsworth-kelly",
          name: "Ellsworth Kelly",
        },
      ],
      artist_names: "Ellsworth Kelly",
      image: {
        aspect_ratio: 0.74,
        id: "5b4b7c655a8a0c02f6df7999",
        url: "https://d32dm0rphc51dk.cloudfront.net/Cut7VPHWKBilZ5Ivj5vJIg/larger.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/Cut7VPHWKBilZ5Ivj5vJIg/larger.jpg",
          aspect_ratio: 0.74,
          id: "5b4b7c655a8a0c02f6df7999",
        },
      ],
      href: "/artwork/ellsworth-kelly-green-curve-14",
      sale: null,
      is_in_auction: false,
      sale_message: "$10,500",
      price: "$10,500",
      availability: "for sale",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "2000",
    },
    {
      gravityID: "QXJ0d29yazp3b2xmLWthaG4taW4taXBzd2ljaC1tYXNz",
      id: "wolf-kahn-in-ipswich-mass",
      title: "In Ipswich, Mass",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "wolf-kahn",
          name: "Wolf Kahn",
        },
      ],
      artist_names: "Wolf Kahn",
      image: {
        aspect_ratio: 1.35,
        id: "5b4b7a60031bec5fa824e4d7",
        url: "https://d32dm0rphc51dk.cloudfront.net/qY9kBnLdh2EPkPZK8VuAaA/larger.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/qY9kBnLdh2EPkPZK8VuAaA/larger.jpg",
          aspect_ratio: 1.35,
          id: "5b4b7a60031bec5fa824e4d7",
        },
      ],
      href: "/artwork/wolf-kahn-in-ipswich-mass",
      sale: null,
      is_in_auction: false,
      sale_message: "$9,500",
      price: "$9,500",
      availability: "for sale",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1987",
    },
    {
      gravityID: "QXJ0d29yazpkYXZpZC1ob2NrbmV5LW15LXBvb2wtYW5kLXRlcnJhY2UtNA==",
      id: "david-hockney-my-pool-and-terrace-4",
      title: "My Pool & Terrace",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "david-hockney",
          name: "David Hockney",
        },
      ],
      artist_names: "David Hockney",
      image: {
        aspect_ratio: 1.48,
        id: "5b4b7596c3f01104a3b8cd03",
        url: "https://d32dm0rphc51dk.cloudfront.net/05rL1DSRwbn9t43xoYkiLg/larger.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/05rL1DSRwbn9t43xoYkiLg/larger.jpg",
          aspect_ratio: 1.48,
          id: "5b4b7596c3f01104a3b8cd03",
        },
      ],
      href: "/artwork/david-hockney-my-pool-and-terrace-4",
      sale: null,
      is_in_auction: false,
      sale_message: "Sold",
      price: "$13,000",
      availability: "sold",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1983",
    },
    {
      gravityID: "QXJ0d29yazp3b2xmLWthaG4tb3JjaGFyZC1hdC1kdXNr",
      id: "wolf-kahn-orchard-at-dusk",
      title: "Orchard at Dusk",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "wolf-kahn",
          name: "Wolf Kahn",
        },
      ],
      artist_names: "Wolf Kahn",
      image: {
        aspect_ratio: 1.25,
        id: "5b4b7a3fc4c7147ec8ed12b8",
        url: "https://d32dm0rphc51dk.cloudfront.net/7YGi2ogpyQW4Vl9gorV0dQ/larger.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/7YGi2ogpyQW4Vl9gorV0dQ/larger.jpg",
          aspect_ratio: 1.25,
          id: "5b4b7a3fc4c7147ec8ed12b8",
        },
      ],
      href: "/artwork/wolf-kahn-orchard-at-dusk",
      sale: null,
      is_in_auction: false,
      sale_message: "$8,000",
      price: "$8,000",
      availability: "for sale",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1989",
    },
    {
      gravityID: "QXJ0d29yazpoYW5zLWhvZm1hbm4tdW50aXRsZWQtMjIx",
      id: "hans-hofmann-untitled-221",
      title: "Untitled",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "hans-hofmann",
          name: "Hans Hofmann",
        },
      ],
      artist_names: "Hans Hofmann",
      image: {
        aspect_ratio: 0.82,
        id: "5b4b7872841d6662f71bb141",
        url: "https://d32dm0rphc51dk.cloudfront.net/WPV9hXX5oms437ujKpPdGg/larger.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/WPV9hXX5oms437ujKpPdGg/larger.jpg",
          aspect_ratio: 0.82,
          id: "5b4b7872841d6662f71bb141",
        },
      ],
      href: "/artwork/hans-hofmann-untitled-221",
      sale: null,
      is_in_auction: false,
      sale_message: "$5,000",
      price: "$5,000",
      availability: "for sale",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1942",
    },
    {
      gravityID: "QXJ0d29yazpwb2xseS1hcGZlbGJhdW0tbG92ZS1tZS10ZW5kZXItaWk=",
      id: "polly-apfelbaum-love-me-tender-ii",
      title: "Love Me Tender II",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "polly-apfelbaum",
          name: "Polly Apfelbaum",
        },
      ],
      artist_names: "Polly Apfelbaum",
      image: {
        aspect_ratio: 1,
        id: "5b4cccb8efdaeb002387b941",
        url: "https://d32dm0rphc51dk.cloudfront.net/HPFxUT7W1lV6UwRu3PvlRQ/larger.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/HPFxUT7W1lV6UwRu3PvlRQ/larger.jpg",
          aspect_ratio: 1,
          id: "5b4cccb8efdaeb002387b941",
        },
      ],
      href: "/artwork/polly-apfelbaum-love-me-tender-ii",
      sale: null,
      is_in_auction: false,
      sale_message: "Sold",
      price: "$8,000",
      availability: "sold",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "",
    },
    {
      gravityID: "QXJ0d29yazpicmlkZ2V0LXJpbGV5LWJsdWUtZG9taW5hbmNl",
      id: "bridget-riley-blue-dominance",
      title: "Blue Dominance",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "bridget-riley",
          name: "Bridget Riley",
        },
      ],
      artist_names: "Bridget Riley",
      image: {
        aspect_ratio: 0.5,
        id: "5b4b64635a8a0c796e7ee64f",
        url: "https://d32dm0rphc51dk.cloudfront.net/SvWPlpYA25k-5Kje-Lp8rg/medium.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/SvWPlpYA25k-5Kje-Lp8rg/medium.jpg",
          aspect_ratio: 0.5,
          id: "5b4b64635a8a0c796e7ee64f",
        },
      ],
      href: "/artwork/bridget-riley-blue-dominance",
      sale: null,
      is_in_auction: false,
      sale_message: "$15,000",
      price: "$15,000",
      availability: "for sale",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1977",
    },
    {
      id:
        "QXJ0d29yazpwYWJsby1waWNhc3NvLW1vZGVsLWNvbnRlbXBsYXRpbmctYS1ncm91cC1vZi1zY3VscHR1cmVzLW1vZGVsZS1jb250ZW1wbGFudC11bi1ncm91cGUtc2N1bHB0ZQ==",
      gravityID: "pablo-picasso-model-contemplating-a-group-of-sculptures-modele-contemplant-un-groupe-sculpte",
      title: "Model Contemplating a Group of Sculptures (Modele Contemplant Un Groupe Sculpte)",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "pablo-picasso",
          name: "Pablo Picasso",
        },
      ],
      artist_names: "Pablo Picasso",
      image: {
        aspect_ratio: 1.21,
        id: "5b4b9901640675075eedee14",
        url: "https://d32dm0rphc51dk.cloudfront.net/leU66mGhe0D2OvMQmGRt4Q/large_rectangle.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/leU66mGhe0D2OvMQmGRt4Q/large_rectangle.jpg",
          aspect_ratio: 1.21,
          id: "5b4b9901640675075eedee14",
        },
      ],
      href: "/artwork/pablo-picasso-model-contemplating-a-group-of-sculptures-modele-contemplant-un-groupe-sculpte",
      sale: null,
      is_in_auction: false,
      sale_message: "Sold",
      price: "",
      availability: "sold",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "1933",
    },
    {
      gravityID: "QXJ0d29yazpkYWxlLWNoaWh1bHktY2VsdGljLWVtZXJhbGQtcGVyc2lhbi1wYWly",
      id: "dale-chihuly-celtic-emerald-persian-pair",
      title: "Celtic Emerald Persian Pair",
      partner: {
        __typename: "Partner",
        name: "Anderson Fine Art Gallery",
        href: "/anderson-fine-art",
        id: "anderson-fine-art-gallery",
      },
      artists: [
        {
          id: "dale-chihuly",
          name: "Dale Chihuly",
        },
      ],
      artist_names: "Dale Chihuly",
      image: {
        aspect_ratio: 1.5,
        id: "5b4b9d53a7bb3b3b27bcec67",
        url: "https://d32dm0rphc51dk.cloudfront.net/6hN0QtT-BQE2y8LGhiI3EA/medium.jpg",
      },
      images: [
        {
          url: "https://d32dm0rphc51dk.cloudfront.net/6hN0QtT-BQE2y8LGhiI3EA/medium.jpg",
          aspect_ratio: 1.5,
          id: "5b4b9d53a7bb3b3b27bcec67",
        },
      ],
      href: "/artwork/dale-chihuly-celtic-emerald-persian-pair",
      sale: null,
      is_in_auction: false,
      sale_message: "Sold",
      price: "",
      availability: "sold",
      contact_label: "Gallery",
      sale_artwork: null,
      is_biddable: false,
      is_offerable: false,
      is_acquireable: false,
      date: "",
    },
  ],
  counts: {
    artists: 17,
    artworks: 21,
    eligible_artworks: 21,
  },
  name: "Flickinger Collection",
  description:
    "Masterworks on paper, prints, paintings, and sculptures by mainstay postwar and contemporary artists are the focus in this exclusive exhibition showcasing the discerning connoisseurship of Tom & Penny Flickinger, lifelong collectors, and trustees of the Albright Knox Art Gallery.",
  press_release:
    "Paintings and Sculpture from the Sea Island Estate of the Flickingers will be offered for sale through the Anderson Fine Art Gallery, online and by appointment. Acquired over a 40 year period, the collection consists of post-war to contemporary paintings and works on paper.  The artwork was purchased from major dealers in New York, Chicago and London and reflects the passion, education and knowledge of Tom and Penny Flickinger whose intellectual discovery and visual pleasure guided their choices. \r\n\r\nThe collection includes works by Richard Diebenkorn, David Hockney, Joan Mitchell and Wolf Kahn, to name a few. A portion of the proceeds will be donated to the St. Simons Land Trust.",
  exhibition_period: "Jul 1 – Oct 30",
  status_update: "Closing tomorrow",
  images: [
    {
      url: "https://d32dm0rphc51dk.cloudfront.net/Bu7ONuoTlR-PLZDUjs6ZTA/medium.jpg",
      aspect_ratio: 0.87,
    },
  ],
  filteredArtworks: {
    aggregations: [
      {
        slice: "PRICE_RANGE",
        counts: [
          {
            id: "*-*",
            name: "for Sale",
          },
          {
            id: "10000-50000",
            name: "between $10,000 & $50,000",
          },
          {
            id: "5000-10000",
            name: "between $5,000 & $10,000",
          },
          {
            id: "1000-5000",
            name: "between $1,000 & $5,000",
          },
          {
            id: "*-1000",
            name: "Under $1,000",
          },
        ],
      },
      {
        slice: "MEDIUM",
        counts: [
          {
            id: "painting",
            name: "Painting",
          },
          {
            id: "prints",
            name: "Prints",
          },
          {
            id: "work-on-paper",
            name: "Work on Paper",
          },
          {
            id: "drawing",
            name: "Drawing",
          },
          {
            id: "sculpture",
            name: "Sculpture",
          },
        ],
      },
    ],
    artworks_connection: {
      edges: [
        {
          node: {
            id: "david-hockney-my-pool-and-terrace-4",
            title: "My Pool & Terrace",
            date: "1983",
            sale_message: "$13,000",
            is_in_auction: false,
            is_biddable: false,
            is_acquireable: false,
            sale: null,
            sale_artwork: null,
            image: {
              url: "https://d32dm0rphc51dk.cloudfront.net/05rL1DSRwbn9t43xoYkiLg/large.jpg",
              aspect_ratio: 1.48,
            },
            artists: [
              {
                name: "David Hockney",
              },
            ],
            partner: {
              name: "Anderson Fine Art Gallery",
            },
            href: "/artwork/david-hockney-my-pool-and-terrace-4",
          },
        },
        {
          node: {
            id: "bridget-riley-blue-dominance",
            title: "Blue Dominance",
            date: "1977",
            sale_message: "$15,000",
            is_in_auction: false,
            is_biddable: false,
            is_acquireable: false,
            sale: null,
            sale_artwork: null,
            image: {
              url: "https://d32dm0rphc51dk.cloudfront.net/SvWPlpYA25k-5Kje-Lp8rg/large.jpg",
              aspect_ratio: 0.5,
            },
            artists: [
              {
                name: "Bridget Riley",
              },
            ],
            partner: {
              name: "Anderson Fine Art Gallery",
            },
            href: "/artwork/bridget-riley-blue-dominance",
          },
        },
        {
          node: {
            id: "hans-hofmann-untitled-221",
            title: "Untitled",
            date: "1942",
            sale_message: "$5,000",
            is_in_auction: false,
            is_biddable: false,
            is_acquireable: false,
            sale: null,
            sale_artwork: null,
            image: {
              url: "https://d32dm0rphc51dk.cloudfront.net/WPV9hXX5oms437ujKpPdGg/large.jpg",
              aspect_ratio: 0.82,
            },
            artists: [
              {
                name: "Hans Hofmann",
              },
            ],
            partner: {
              name: "Anderson Fine Art Gallery",
            },
            href: "/artwork/hans-hofmann-untitled-221",
          },
        },
        {
          node: {
            id: "wolf-kahn-orchard-at-dusk",
            title: "Orchard at Dusk",
            date: "1989",
            sale_message: "$8,000",
            is_in_auction: false,
            is_biddable: false,
            is_acquireable: false,
            sale: null,
            sale_artwork: null,
            image: {
              url: "https://d32dm0rphc51dk.cloudfront.net/7YGi2ogpyQW4Vl9gorV0dQ/large.jpg",
              aspect_ratio: 1.25,
            },
            artists: [
              {
                name: "Wolf Kahn",
              },
            ],
            partner: {
              name: "Anderson Fine Art Gallery",
            },
            href: "/artwork/wolf-kahn-orchard-at-dusk",
          },
        },
        {
          node: {
            id: "wolf-kahn-in-ipswich-mass",
            title: "In Ipswich, Mass",
            date: "1987",
            sale_message: "$9,500",
            is_in_auction: false,
            is_biddable: false,
            is_acquireable: false,
            sale: null,
            sale_artwork: null,
            image: {
              url: "https://d32dm0rphc51dk.cloudfront.net/qY9kBnLdh2EPkPZK8VuAaA/large.jpg",
              aspect_ratio: 1.35,
            },
            artists: [
              {
                name: "Wolf Kahn",
              },
            ],
            partner: {
              name: "Anderson Fine Art Gallery",
            },
            href: "/artwork/wolf-kahn-in-ipswich-mass",
          },
        },
        {
          node: {
            id: "marc-hanson-scrappy",
            title: "Scrappy",
            date: "ca. 2018",
            sale_message: "$10,300",
            is_in_auction: false,
            is_biddable: false,
            is_acquireable: false,
            sale: null,
            sale_artwork: null,
            image: {
              url: "https://d32dm0rphc51dk.cloudfront.net/GSzNrBCUurMHdNEgT6LdwQ/large.jpg",
              aspect_ratio: 1.33,
            },
            artists: [
              {
                name: "Marc Hanson",
              },
            ],
            partner: {
              name: "Anderson Fine Art Gallery",
            },
            href: "/artwork/marc-hanson-scrappy",
          },
        },
      ],
    },
  },
  artists_grouped_by_name: [
    {
      letter: "A",
      items: [
        {
          gravityID: "polly-apfelbaum",
          id: "QXJ0aXN0OnBvbGx5LWFwZmVsYmF1bQ==",
          name: "Polly Apfelbaum",
          is_followed: false,
          nationality: "American",
          birthday: "1955",
          deathday: "",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/MByqc96STE-fJtW4mZpgSg/tall.jpg",
          },
        },
        {
          gravityID: "karel-appel",
          id: "QXJ0aXN0OmthcmVsLWFwcGVs",
          name: "Karel Appel",
          is_followed: false,
          nationality: "Dutch",
          birthday: "1921",
          deathday: "2006",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/puxzysW1yY3FCRLFaLFEQQ/tall.jpg",
          },
        },
      ],
    },
    {
      letter: "B",
      items: [
        {
          gravityID: "bruce-beasley",
          id: "QXJ0aXN0OmJydWNlLWJlYXNsZXk=",
          name: "Bruce Beasley",
          is_followed: false,
          nationality: "American",
          birthday: "1939",
          deathday: "",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/XazCw3_7ZEQz-sdkLDWXjA/tall.jpg",
          },
        },
        {
          gravityID: "nell-blaine",
          id: "QXJ0aXN0Om5lbGwtYmxhaW5l",
          name: "Nell Blaine",
          is_followed: false,
          nationality: "American",
          birthday: "1922",
          deathday: "1996",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/jr4zSDi7sXllVBNVhQardw/tall.jpg",
          },
        },
        {
          gravityID: "carolyn-brady",
          id: "QXJ0aXN0OmNhcm9seW4tYnJhZHk=",
          name: "Carolyn Brady",
          is_followed: false,
          nationality: "American",
          birthday: "1937",
          deathday: "2005",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/DH5Jtvy_a5d4Bb5hxB-Fxw/tall.jpg",
          },
        },
      ],
    },
    {
      letter: "C",
      items: [
        {
          gravityID: "dale-chihuly",
          id: "QXJ0aXN0OmRhbGUtY2hpaHVseQ==",
          name: "Dale Chihuly",
          is_followed: false,
          nationality: "American",
          birthday: "1941",
          deathday: "",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/qfT1qZw8EGJguSakyhFxig/tall.jpg",
          },
        },
      ],
    },
    {
      letter: "D",
      items: [
        {
          gravityID: "richard-diebenkorn",
          id: "QXJ0aXN0OnJpY2hhcmQtZGllYmVua29ybg==",
          name: "Richard Diebenkorn",
          is_followed: false,
          nationality: "American",
          birthday: "1922",
          deathday: "1993",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/C5GfncAzGMsMf6A6RSfJEQ/tall.jpg",
          },
        },
        {
          gravityID: "jim-dine",
          id: "QXJ0aXN0OmppbS1kaW5l",
          name: "Jim Dine",
          is_followed: false,
          nationality: "American",
          birthday: "1935",
          deathday: "",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/Ll4gMf_OsLMehbgv05H6mw/tall.jpg",
          },
        },
      ],
    },
    {
      letter: "F",
      items: [
        {
          gravityID: "sam-francis",
          id: "QXJ0aXN0OnNhbS1mcmFuY2lz",
          name: "Sam Francis",
          is_followed: false,
          nationality: "American",
          birthday: "1923",
          deathday: "1994",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/wZ9dabmVZjtcaB_q_bKKzw/tall.jpg",
          },
        },
      ],
    },
    {
      letter: "H",
      items: [
        {
          gravityID: "robert-harms",
          id: "QXJ0aXN0OnJvYmVydC1oYXJtcw==",
          name: "Robert Harms",
          is_followed: false,
          nationality: "",
          birthday: "1962",
          deathday: "",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/i5_X3qJO8gFiyHrlHvAb-w/tall.jpg",
          },
        },
        {
          gravityID: "david-hockney",
          id: "QXJ0aXN0OmRhdmlkLWhvY2tuZXk=",
          name: "David Hockney",
          is_followed: false,
          nationality: "British",
          birthday: "1937",
          deathday: "",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/kCJVZo7bcqVrjnQ22QHhvg/tall.jpg",
          },
        },
        {
          gravityID: "hans-hofmann",
          id: "QXJ0aXN0OmhhbnMtaG9mbWFubg==",
          name: "Hans Hofmann",
          is_followed: false,
          nationality: "German-American",
          birthday: "1880",
          deathday: "1966",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/vRQdNHjLuWKadBXy9Fl4Pg/tall.jpg",
          },
        },
      ],
    },
    {
      letter: "K",
      items: [
        {
          gravityID: "wolf-kahn",
          id: "QXJ0aXN0OndvbGYta2Fobg==",
          name: "Wolf Kahn",
          is_followed: false,
          nationality: "American",
          birthday: "1927",
          deathday: "",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/pzYQSjFUn7MyELRIVyADjQ/tall.jpg",
          },
        },
        {
          gravityID: "ellsworth-kelly",
          id: "QXJ0aXN0OmVsbHN3b3J0aC1rZWxseQ==",
          name: "Ellsworth Kelly",
          is_followed: false,
          nationality: "American",
          birthday: "1923",
          deathday: "2015",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/Bv9Hh3cYTCvc76NnZS4w4g/tall.jpg",
          },
        },
      ],
    },
    {
      letter: "M",
      items: [
        {
          gravityID: "robert-motherwell",
          id: "QXJ0aXN0OnJvYmVydC1tb3RoZXJ3ZWxs",
          name: "Robert Motherwell",
          is_followed: false,
          nationality: "American",
          birthday: "1915",
          deathday: "1991",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/BbPC9SljRn-_6AfewiQpxw/tall.jpg",
          },
        },
      ],
    },
    {
      letter: "P",
      items: [
        {
          gravityID: "pablo-picasso",
          id: "QXJ0aXN0OnBhYmxvLXBpY2Fzc28=",
          name: "Pablo Picasso",
          is_followed: false,
          nationality: "Spanish",
          birthday: "1881",
          deathday: "1973",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/i3rCA3IaKE-cLBnc-U5swQ/tall.jpg",
          },
        },
      ],
    },
    {
      letter: "R",
      items: [
        {
          gravityID: "bridget-riley",
          id: "QXJ0aXN0OmJyaWRnZXQtcmlsZXk=",
          name: "Bridget Riley",
          is_followed: false,
          nationality: "British",
          birthday: "1931",
          deathday: "",
          image: {
            url: "https://d32dm0rphc51dk.cloudfront.net/zLIFDjlzCw8ijOH9PPeasA/tall.jpg",
          },
        },
      ],
    },
  ],
  events: [
    {
      event_type: "Opening Reception",
      description: "",
      title: "",
      start_at: "2018-11-02T18:00:00+00:00",
      end_at: "2018-11-02T21:00:00+00:00",
    },
    {
      event_type: "Guided Tour",
      description: "Keith Macgregor will take visitors around the gallery and share his stories.",
      title: "",
      start_at: "2018-11-10T11:00:00+00:00",
      end_at: "2018-11-10T12:00:00+00:00",
    },
    {
      event_type: "Artist Talk",
      description: "Meet and greet Keith Macgregor who will be glad to share his stories and answer your questions.",
      title: "",
      start_at: "2018-11-10T14:00:00+00:00",
      end_at: "2018-11-10T18:00:00+00:00",
    },
  ],
}
