// This file is automatically generated by vscode-react-native@0.1.4
// Please do not modify it manually. All changes will be lost.
try {
    var path = require("path");
    var Launcher = require("/Users/sarahscott/.vscode/extensions/vsmobile.vscode-react-native-0.1.4/out/debugger/launcher.js").Launcher;
    new Launcher(path.resolve(__dirname, "..")).launch();
} catch (e) {
    throw new Error("Unable to launch application. Try deleting .vscode/launchReactNative.js and restarting vscode.");
}