#!/usr/bin/env bash
set -euxo pipefail

./scripts/setup-distribute-linux

yarn jetifier

cd android
touch android/app/src/main/assets/index.android.bundle && yarn bundle:android
./gradlew clean
./gradlew bundleRelease --no-daemon -x bundleReleaseJsAndAssets
cd -
