#!/usr/bin/env bash
set -euxo pipefail

./scripts/setup-distribute

yarn jetifier

cd android
mkdir -p android/app/src/main/assets
touch android/app/src/main/assets/index.android.bundle && yarn bundle:android
./gradlew clean
./gradlew bundleRelease --no-daemon -x bundleReleaseJsAndAssets
cd -
