#!/usr/bin/env bash
set -euxo pipefail


source ./scripts/source-for-bash-env

xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration "$CONFIGURATION" -sdk iphonesimulator build -destination platform="$DEVICE_HOST_PLAT",OS="$DEVICE_HOST_OS",name="$DEVICE_HOST_NAME" -derivedDataPath "$DERIVED_DATA_PATH" |
	tee ./xcode_build_raw.log |
	bundle exec xcpretty -c
