#!/usr/bin/env bash
set -euxo pipefail


source ./scripts/source-for-bash-env

if [ "${LOCAL_BRANCH}" != "beta-android" ] && [ "${LOCAL_BRANCH}" != "app_store_submission" ]; then
	./scripts/test-android
else
	echo "Skipping test run on beta deploy."
fi
