#!/usr/bin/env bash
set -euo pipefail


yarn detect-secrets-launcher --baseline .secrets.baseline --exclude-secrets '[a-fA-F0-9]{24}' --exclude-lines 'W/"[!#-\x7E]*"' $(git diff --staged --name-only | grep -v stickerpack) || git add .secrets.baseline
