#!/usr/bin/env bash
set -euxo pipefail

./scripts/setup-distribute

DISTRIBUTION_TARGET="${1-"PLAY_STORE"}"
if [ $DISTRIBUTION_TARGET == "FIREBASE" ]; then
  bundle exec fastlane ship_beta_android_firebase
elif [ $DISTRIBUTION_TARGET == "PLAY_STORE" ]; then
  bundle exec fastlane ship_beta_android_play_store
elif [ $DISTRIBUTION_TARGET == "BOTH" ]; then
  bundle exec fastlane ship_beta_android_firebase
  bundle exec fastlane ship_beta_android_play_store
fi
