#!/usr/bin/env bash
set -euxo pipefail


# Get fonts from eigen s3 bucket
aws s3 cp s3://artsy-citadel/eigen/fonts.tar.gz ./fonts.tar.gz

# Extract fonts
mkdir -p ./fonts
tar -xvzf fonts.tar.gz -C ./fonts

# Android
cp ./fonts/android/* android/app/src/main/assets/fonts

# iOS
# old ios
mkdir -p ./Pods/Artsy+UIFonts/Pod/Assets
cp ./fonts/ios/* Pods/Artsy+UIFonts/Pod/Assets
# new ios
cp ./fonts/ios/* ios/eigen/fonts

# Cleanup
rm -rf ./fonts.tar.gz
rm -rf ./fonts
