#!/usr/bin/env bash
set -euxo pipefail


# Get fonts from eigen s3 bucket
aws s3 cp s3://artsy-citadel/eigen/fonts.tar.gz ./fonts.tar.gz

# Extract fonts
mkdir -p ./fonts
tar -xvzf fonts.tar.gz -C ./fonts

# Android
mkdir -p android/app/src/main/assets/fonts
cp ./fonts/android/* android/app/src/main/assets/fonts

# iOS
# for now, ios is handled in the UIFonts pod. we should change that to be somewhere in our project dir.

# Cleanup
rm -rf ./fonts.tar.gz
rm -rf ./fonts
