#!/usr/bin/env bash
set -euxo pipefail


# Clear global and local caches and build files
echo 'Clean global yarn & pod caches (┛✧Д✧))┛彡┻━┻'
yarn cache clean
bundle exec pod cache clean --all
./scripts/flip-table
