#!/usr/bin/env bash
set -euxo pipefail


bundle check || bundle install
brew install detect-secrets # using brew version. read more here: https://github.com/artsy/homebrew-formulas/pull/13
yarn install
yarn pod-install
