#!/usr/bin/env bash
set -euxo pipefail


source ./scripts/source-for-bash-env

if [ "${LOCAL_BRANCH}" == "app_store_submission" ]; then
	./scripts/setup-fastlane-env
	bundle exec fastlane update_plugins
	bundle exec fastlane promote_beta_ios
fi
