#!/usr/bin/env bash
set -euxo pipefail


source ./scripts/source-for-bash-env

if [ "${LOCAL_BRANCH}" == "release-ios-app" ]; then
	./scripts/setup-fastlane-env
	bundle exec fastlane update_plugins
	bundle exec fastlane release_ios_app
fi
