#!/usr/bin/env bash
set -euxo pipefail

# This script runs to make sure staged files don't contain secrets.

git diff --staged --name-only \
| tr '\n' '\0' \
| xargs -0 detect-secrets-hook \
  --baseline .secrets.baseline \
  --verbose
