#!/usr/bin/env bash
set -euxo pipefail

# This script runs to make sure all repo files don't contain secrets.

git ls-files \
| tr '\n' '\0' \
| xargs -0 detect-secrets-hook \
  --baseline .secrets.baseline \
  --verbose
