#!/usr/bin/env bash
set -euxo pipefail

touch .env.ci
cp .env.example .env.shared

# Set the OSS flag to true
sed 's/OSS=.*/OSS=True/g' .env.shared

cp metaflags.example.json metaflags.json

./scripts/setup-oss-fonts