#!/usr/bin/env bash
set -euxo pipefail

cp .env.example .env.shared

# Set the OSS flag to true
sed -i'old' 's/OSS=.*/OSS=True/g' .env.shared

cp metaflags.example.json metaflags.json

./scripts/setup-oss-fonts