#!/usr/bin/env bash
set -euxo pipefail


./scripts/setup-fastlane-env
brew update
brew tap getsentry/tools
brew install sentry-cli
bundle exec fastlane update_plugins

aws s3 cp s3://artsy-citadel/eigen/GoogleService-Info.plist GoogleService-Info.plist