#!/usr/bin/env bash
set -euxo pipefail


./scripts/setup-fastlane-env
brew update
brew tap getsentry/tools
brew install sentry-cli
bundle exec fastlane update_plugins

if ! which aws;
then
  echo "installing aws"
  # install awscli
  curl "https://awscli.amazonaws.com/awscli-exe-linux-macos.zip" -o "awscliv2.zip"
  unzip -o -qq awscliv2.zip
  sudo ./aws/install

  # configure awscli
  mkdir -p ~/.aws
  touch ~/.aws/config
  echo "[default]" >> ~/.aws/config
  echo "region = us-east-1" >> ~/.aws/config
  echo "output = json" >> ~/.aws/config
else
  echo "aws already installed"
fi

aws s3 cp s3://artsy-citadel/eigen/GoogleService-Info.plist GoogleService-Info.plist