#!/usr/bin/env bash
set -euxo pipefail


source ./scripts/setup/source-for-bash-env

xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug test -sdk iphonesimulator -destination platform="$DEVICE_HOST_PLAT",OS="$DEVICE_HOST_OS",name="$DEVICE_HOST_NAME" -derivedDataPath "$DERIVED_DATA_PATH" GCC_PREPROCESSOR_DEFINITIONS='$(inherited) CI_DISABLE_FLIPPER=1' |
	tee ./xcode_test_raw.log |
	bundle exec xcpretty -c --test --report junit --output ./test-results.xml
