export const getRandomAutomatedMessage = () => {
  return AUTOMATED_MESSAGES[Math.floor(Math.random() * AUTOMATED_MESSAGES.length)]
}

const AUTOMATED_MESSAGES = [
  "Hi, I’m interested in purchasing this work. Could you please provide more information about the piece?",
  "Hello, I'm interested in this artwork. Could you provide more details about it?",
  "Hi, I came across this piece and would love to learn more about it. Can you provide additional information?",
  "Hi there, I'm interested in buying this work. Could you please share some more information about it?",
  "Hello, I'm interested in this piece. Could you please provide me with more information about it?",
  "Hi, I would love to add this artwork to my collection. Could you please provide me with more details?",
  "Hi there, I'm interested in this piece. Could you please provide me with additional details?",
  "Hello, I'm interested in purchasing this artwork. Can you provide me with more information about it?",
  "Hi, I'm interested in this piece and would love to know more about it. Could you please provide additional information?",
  "Hi there, I'm interested in this piece and would like to learn more about it. Could you please provide additional details?",
  "Hello, I'm considering purchasing this artwork. Can you provide me with more information about the piece?",
  "Hi, I'm interested in this work and would love to know more about it. Could you please provide additional information?",
  "Hi there! Can you tell me more about this artwork? I'm very interested in it.",
  "Hello, this artwork caught my eye. Any chance you could provide me with more details about it?",
  "Hi, I'd love to learn more about this artwork! Could you tell me more about it?",
  "Hello! Could you give me some additional information about this artwork? I'm really interested in it.",
  "I'm very interested in this artwork. Could you please provide me with more details about it?",
  "This artwork is fascinating! Could you please share some additional information about it?",
  "Hi there! I'd like to know more about this piece. Could you tell me about it?",
  "I'm very interested in this artwork. Would you mind providing me with more information about it?",
  "I'd like to know more about this work. Could you share some additional information with me?",
  "Hello! I was intrigued by this artwork. Could you please provide me with more details about it?",
  "I'm very interested in this artwork. Can you give me more information about it?",
  "Hi there! I saw this artwork and thought it was captivating. Could you tell me more about it?",
  "I'm intrigued by this artwork. Could you please tell me more about it?",
  "Hello, I'm interested in learning more about this artwork. Could you provide me with additional details?",
  "Hi there! This artwork is stunning. Can you tell me more about it?",
  "I'm very interested in this artwork. Would you mind giving me more details about it?",
  "Hello! Could you please provide me with more details about this artwork? I'm quite interested in it.",
  "Hello, I'm interested in this work. Could you share some additional information with me about it?",
  "I'm interested in learning more about this piece. Can you tell me more about it?",
  "Hi there. I came across this artwork today. Could you please provide me with more information about it?",
  "Hello, I'm interested in this artwork and would love to know more about it.",
  "Hi, I collect art and was intrigued by this artwork. Can you provide additional information?",
  "Hello, I'm a collector and would like to inquire about this artwork. Could you please share more details?",
  "Hi, I'm very interested in this artwork and would appreciate more information about it.",
  "Hi there, I'm interested in this artwork and would like to know more about it. Can you provide further information?",
  "Hello, I'm a collector and would love to learn more about this artwork. Could you please share additional details?",
  "Hi, as someone who collects art, I was intrigued by this piece. Can you provide more information about it?",
  "Hi, I'm a collector and would like to know more about this artwork. Can you please provide additional information?",
]
