name: Setup repository environment
description: "Setup repository with, AWS credentials, and environment files"
inputs:
  aws-access-key-id:
    description: "AWS access key ID"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS region"
    required: false
    default: "us-east-1"
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Set up environment for CI
      run: |
        touch .env.shared && touch keys.shared.json
        scripts/setup/setup-env-for-ci
        echo "Environment setup completed"
      shell: bash
