
/**
 * Do NOT alter this file directly! It is auto-generated by the `./scripts/generate-cities-objc.js` script.
 */

#import "ARCity.h"

@interface ARCity ()

- (instancetype)initWithName:(NSString *)name slug:(NSString *)slug epicenter:(CLLocation *)epicenter;

@end

@implementation ARCity

- (instancetype)initWithName:(NSString *)name slug:(NSString *)slug epicenter:(CLLocation *)epicenter;
{
    self = [super init];
    if (self) {
        _name = name;
        _slug = slug;
        _epicenter = epicenter;
    }
    return self;
}

+ (NSArray <ARCity *> *)cities
{
    static NSArray <ARCity *> *_computedCities = nil;
    if (!_computedCities) {
        _computedCities = @[
            [[ARCity alloc] initWithName:@"New York" slug:@"new-york-ny-usa" epicenter:[[CLLocation alloc] initWithLatitude:40.713 longitude:-74.006]],
            [[ARCity alloc] initWithName:@"Los Angeles" slug:@"los-angeles-ca-usa" epicenter:[[CLLocation alloc] initWithLatitude:34.052 longitude:-118.244]],
            [[ARCity alloc] initWithName:@"London" slug:@"london-united-kingdom" epicenter:[[CLLocation alloc] initWithLatitude:51.507 longitude:-0.128]],
            [[ARCity alloc] initWithName:@"Berlin" slug:@"berlin-germany" epicenter:[[CLLocation alloc] initWithLatitude:52.52 longitude:13.405]],
            [[ARCity alloc] initWithName:@"Paris" slug:@"paris-france" epicenter:[[CLLocation alloc] initWithLatitude:48.857 longitude:2.352]],
            [[ARCity alloc] initWithName:@"Hong Kong" slug:@"hong-kong-hong-kong" epicenter:[[CLLocation alloc] initWithLatitude:22.282 longitude:114.158]]
        ];
    }
    return _computedCities;
}

@end
