#!/bin/bash
set -euo pipefail

# fetch the latest description from the deployment history the naming patern is "some description version:expo-canary-ios-8.39.0-2024.05.10.09"
description=$(eas update:list --branch=canary --json --non-interactive | jq .currentPage[0].message)

# extract the version from the description
if [[ $description =~ version:(.*) ]]; then
  extracted_string="${BASH_REMATCH[1]}"
    # Trim any leading or trailing whitespace
  extracted_string=$(echo "$extracted_string" | xargs)
  modified_string="${extracted_string//staging/submission}"
  modified_string="${modified_string//canary/submission}"
  echo "$modified_string"
fi