#!/bin/bash

# === CONFIG ===
IOS_PLIST_PATH="ios/Artsy/Supporting/Expo.plist"
IOS_QA_PLIST_PATH="ios/Artsy/Supporting/QA/ExpoQA.plist"
APP_JSON_PATH="app.json"

native_fingerprint=$(npx @expo/fingerprint fingerprint:generate | jq -r '.hash')

echo "Updating iOS Expo.plist with runtimeVersion = $native_fingerprint"
/usr/libexec/PlistBuddy -c "Set :EXUpdatesRuntimeVersion $native_fingerprint" "$IOS_PLIST_PATH"

echo "Updating iOS ExpoQA.plist with runtimeVersion = $native_fingerprint"
/usr/libexec/PlistBuddy -c "Set :EXUpdatesRuntimeVersion $native_fingerprint" "$IOS_QA_PLIST_PATH"

# Update app.json
echo "Updating app.json with runtimeVersion = $native_fingerprint"
tmpfile=$(mktemp)
jq --arg version "$native_fingerprint" '.expo.runtimeVersion = $version' "$APP_JSON_PATH" > "$tmpfile" && mv "$tmpfile" "$APP_JSON_PATH"

# Done
echo -e "\033[0;32mRuntime version updated successfully in iOS and app.json.\033[0m"