#!/bin/bash
set -euxo pipefail

if [ "$#" -lt 1 ] || [ "$#" -gt 1 ]; then
  echo "Usage: $0 <rollout_percentage e.g. 50>"
  exit 1
fi

rollout_percentage=$1

eas update:edit --channel=production --rollout-percentage=$rollout_percentage